/* SPDX-License-Identifier: LGPL-2.1 */

/*
 * mtd.h - Make Tax Digital
 *
 * Copyright (C) 2020 - 2022	Andrew Clayton <andrew@digital-domain.net>
 */

#ifndef _MTD_H_
#define _MTD_H_

#include <stdio.h>
#include <sys/types.h>

#ifdef __cplusplus
extern "C" {
#endif

#define LIBMTDAC_MAJOR_VERSION		 0
#define LIBMTDAC_MINOR_VERSION		50
#define LIBMTDAC_MICRO_VERSION		 0

/* MTD_OPT_* - option flags for mtd_init() */
#define MTD_OPT_LOG_ERR				0x00000001
#define MTD_OPT_LOG_INFO			0x00000002
#define MTD_OPT_LOG_DEBUG			0x00000004

/* also update enum app_conn_type in mtd.c */
#define MTD_OPT_ACT_MOBILE_APP_DIRECT		0x00000100
#define MTD_OPT_ACT_DESKTOP_APP_DIRECT		0x00000200
#define MTD_OPT_ACT_MOBILE_APP_VIA_SERVER	0x00000400
#define MTD_OPT_ACT_DESKTOP_APP_VIA_SERVER	0x00000800
#define MTD_OPT_ACT_WEB_APP_VIA_SERVER		0x00001000
#define MTD_OPT_ACT_BATCH_PROCESS_DIRECT	0x00002000
#define MTD_OPT_ACT_OTHER_DIRECT		0x00004000
#define MTD_OPT_ACT_OTHER_VIA_SERVER		0x00008000

#define MTD_OPT_NO_ANTI_FRAUD_HDRS		0x10000000
#define MTD_OPT_SND_EMPTY_HDRS			0x20000000

#define MTD_OPT_GLOBAL_INIT			0x40000000

#define MTD_OPT_PRODUCTION_API			0x80000000

#define MTD_OPT_ALL \
	MTD_OPT_LOG_ERR | \
	MTD_OPT_LOG_INFO | \
	MTD_OPT_LOG_DEBUG | \
	MTD_OPT_ACT_MOBILE_APP_DIRECT | \
	MTD_OPT_ACT_DESKTOP_APP_DIRECT | \
	MTD_OPT_ACT_MOBILE_APP_VIA_SERVER | \
	MTD_OPT_ACT_DESKTOP_APP_VIA_SERVER | \
	MTD_OPT_ACT_WEB_APP_VIA_SERVER | \
	MTD_OPT_ACT_BATCH_PROCESS_DIRECT | \
	MTD_OPT_ACT_OTHER_DIRECT | \
	MTD_OPT_ACT_OTHER_VIA_SERVER | \
	MTD_OPT_NO_ANTI_FRAUD_HDRS | \
	MTD_OPT_SND_EMPTY_HDRS | \
	MTD_OPT_GLOBAL_INIT | \
	MTD_OPT_PRODUCTION_API

enum mtd_error {
	MTD_ERR_NONE = 0,
	MTD_ERR_OS,
	MTD_ERR_REQUEST,
	MTD_ERR_CURL,
	MTD_ERR_NEEDS_AUTHORISATION,
	MTD_ERR_UNKNOWN_FLAGS,
	MTD_ERR_UNKNOWN_SCOPES,
	MTD_ERR_LIB_TOO_OLD,
	MTD_ERR_CONFIG_DIR_UNSPEC,
	MTD_ERR_CONFIG_DIR_INVALID,
	MTD_ERR_NO_CONFIG,
	MTD_ERR_INVALID_EP_API,

	/* keep this last */
	MTD_ERR_INVALID_ERROR
};

enum mtd_hmrc_error {
	MTD_HMRC_ERR_MULTIPLE = 0,

	MTD_HMRC_ERR_CLIENT_OR_AGENT_NOT_AUTHORISED,
	MTD_HMRC_ERR_END_OF_YEAR_ESTIMATE_NOT_PRESENT,
	MTD_HMRC_ERR_FORMAT_ADJUSTED_STATUS,
	MTD_HMRC_ERR_FORMAT_ADJUSTMENT_VALUE,
	MTD_HMRC_ERR_FORMAT_ASSET_DESCRIPTION,
	MTD_HMRC_ERR_FORMAT_ASSET_TYPE,
	MTD_HMRC_ERR_FORMAT_BENEFIT_ID,
	MTD_HMRC_ERR_FORMAT_BENEFIT_TYPE,
	MTD_HMRC_ERR_FORMAT_BSAS_ID,
	MTD_HMRC_ERR_FORMAT_BUSINESS_ID,
	MTD_HMRC_ERR_FORMAT_CALC_ID,
	MTD_HMRC_ERR_FORMAT_CESSATION_DATE,
	MTD_HMRC_ERR_FORMAT_CLAIM_ID,
	MTD_HMRC_ERR_FORMAT_CLAIM_OR_ELECTION_CODES,
	MTD_HMRC_ERR_FORMAT_CLAIM_TYPE,
	MTD_HMRC_ERR_FORMAT_CLASS_OF_SHARES_ACQUIRED,
	MTD_HMRC_ERR_FORMAT_CLASS_OF_SHARES_AWARDED,
	MTD_HMRC_ERR_FORMAT_COUNTRY_CODE,
	MTD_HMRC_ERR_FORMAT_CUSTOMER_REF,
	MTD_HMRC_ERR_FORMAT_CUSTOMER_REFERENCE,
	MTD_HMRC_ERR_FORMAT_DATE,
	MTD_HMRC_ERR_FORMAT_DATE_OF_INVESTMENT,
	MTD_HMRC_ERR_FORMAT_DEDUCTIONS_FROM_DATE,
	MTD_HMRC_ERR_FORMAT_DEDUCTIONS_TO_DATE,
	MTD_HMRC_ERR_FORMAT_DOUBLE_TAXATION_ARTICLE,
	MTD_HMRC_ERR_FORMAT_DOUBLE_TAXATION_TREATY,
	MTD_HMRC_ERR_FORMAT_EMPLOYER_NAME,
	MTD_HMRC_ERR_FORMAT_EMPLOYER_REF,
	MTD_HMRC_ERR_FORMAT_EMPLOYER_REFERENCE,
	MTD_HMRC_ERR_FORMAT_EMPLOYMENT_ID,
	MTD_HMRC_ERR_FORMAT_END_DATE,
	MTD_HMRC_ERR_FORMAT_EVENT,
	MTD_HMRC_ERR_FORMAT_FINALISED,
	MTD_HMRC_ERR_FORMAT_FROM_DATE,
	MTD_HMRC_ERR_FORMAT_ID,
	MTD_HMRC_ERR_FORMAT_INCOME_SOURCE,
	MTD_HMRC_ERR_FORMAT_LENDER_NAME,
	MTD_HMRC_ERR_FORMAT_LOSS_AMOUNT,
	MTD_HMRC_ERR_FORMAT_LOSS_ID,
	MTD_HMRC_ERR_FORMAT_NAME,
	MTD_HMRC_ERR_FORMAT_NAME_BUSINESS,
	MTD_HMRC_ERR_FORMAT_NAME_EX_SPOUSE,
	MTD_HMRC_ERR_FORMAT_NAME_OF_SHIP,
	MTD_HMRC_ERR_FORMAT_NATURE_OF_TRADE,
	MTD_HMRC_ERR_FORMAT_NINO,
	MTD_HMRC_ERR_FORMAT_PAYMENT_ID,
	MTD_HMRC_ERR_FORMAT_PAYROLL_ID,
	MTD_HMRC_ERR_FORMAT_PENSION_SCHEME_TAX_REFERENCE,
	MTD_HMRC_ERR_FORMAT_PPD_SUBMISSION_ID,
	MTD_HMRC_ERR_FORMAT_PROVIDER_NAME,
	MTD_HMRC_ERR_FORMAT_PROVIDERS_ADDRESS,
	MTD_HMRC_ERR_FORMAT_QOPS_REF,
	MTD_HMRC_ERR_FORMAT_SCHEME_PLAN_TYPE,
	MTD_HMRC_ERR_FORMAT_SELF_EMPLOYMENT_ID,
	MTD_HMRC_ERR_FORMAT_SEQUENCE,
	MTD_HMRC_ERR_FORMAT_SF74_REF,
	MTD_HMRC_ERR_FORMAT_SOURCE,
	MTD_HMRC_ERR_FORMAT_SPOUSE_OR_CIVIL_PARTNERS_DATE_OF_BIRTH,
	MTD_HMRC_ERR_FORMAT_SPOUSE_OR_CIVIL_PARTNERS_FIRST_NAME,
	MTD_HMRC_ERR_FORMAT_SPOUSE_OR_CIVIL_PARTNERS_NINO,
	MTD_HMRC_ERR_FORMAT_SPOUSE_OR_CIVIL_PARTNERS_SURNAME,
	MTD_HMRC_ERR_FORMAT_SRN_INVALID,
	MTD_HMRC_ERR_FORMAT_START_DATE,
	MTD_HMRC_ERR_FORMAT_STATUS,
	MTD_HMRC_ERR_FORMAT_STRING,
	MTD_HMRC_ERR_FORMAT_SUBMISSION_ID,
	MTD_HMRC_ERR_FORMAT_TAX_YEAR,
	MTD_HMRC_ERR_FORMAT_TO_DATE,
	MTD_HMRC_ERR_FORMAT_TRANSACTION_ID,
	MTD_HMRC_ERR_FORMAT_TYPE,
	MTD_HMRC_ERR_FORMAT_TYPE_OF_BUSINESS,
	MTD_HMRC_ERR_FORMAT_TYPE_OF_CLAIM,
	MTD_HMRC_ERR_FORMAT_TYPE_OF_LOSS,
	MTD_HMRC_ERR_FORMAT_UNIQUE_INVESTMENT_REFERENCE,
	MTD_HMRC_ERR_FORMAT_VALUE,
	MTD_HMRC_ERR_MATCHING_RESOURCE_NOT_FOUND,
	MTD_HMRC_ERR_MISSING_FROM_DATE,
	MTD_HMRC_ERR_MISSING_TO_DATE,
	MTD_HMRC_ERR_MISSING_TYPE_OF_BUSINESS,
	MTD_HMRC_ERR_NO_BUSINESS_FOUND,
	MTD_HMRC_ERR_NO_DETAILS_FOUND,
	MTD_HMRC_ERR_NO_MESSAGES_PRESENT,
	MTD_HMRC_ERR_NO_OBLIGATIONS_FOUND,
	MTD_HMRC_ERR_PPD_SUBMISSION_ID_NOT_FOUND,
	MTD_HMRC_ERR_RANGE_DATE_TOO_LONG,
	MTD_HMRC_ERR_RANGE_END_DATE_BEFORE_START_DATE,
	MTD_HMRC_ERR_RANGE_TO_DATE_BEFORE_FROM_DATE,
	MTD_HMRC_ERR_RULE_ACCOUNTING_PERIOD_NOT_ENDED,
	MTD_HMRC_ERR_RULE_ACCOUNTING_PERIOD_NOT_SUPPORTED,
	MTD_HMRC_ERR_RULE_ACQUISITION_DATE,
	MTD_HMRC_ERR_RULE_ACQUISITION_DATE_AFTER_DISPOSAL_DATE,
	MTD_HMRC_ERR_RULE_ACTIVE_MARRIAGE_ALLOWANCE_CLAIM,
	MTD_HMRC_ERR_RULE_ALREADY_EXISTS,
	MTD_HMRC_ERR_RULE_ALREADY_SUBMITTED,
	MTD_HMRC_ERR_RULE_AMOUNT_GAIN_LOSS,
	MTD_HMRC_ERR_RULE_BENEFIT_TYPE_EXISTS,
	MTD_HMRC_ERR_RULE_BOTH_ALLOWANCES_SUPPLIED,
	MTD_HMRC_ERR_RULE_BOTH_EXPENSES_SUPPLIED,
	MTD_HMRC_ERR_RULE_BSAS_ALREADY_ADJUSTED,
	MTD_HMRC_ERR_RULE_BUILDING_NAME_NUMBER,
	MTD_HMRC_ERR_RULE_BUSINESS_ID,
	MTD_HMRC_ERR_RULE_BUSINESS_VALIDATION_FAILURE,
	MTD_HMRC_ERR_RULE_CALCULATION_ERROR_MESSAGES_EXIST,
	MTD_HMRC_ERR_RULE_CESSATION_DATE_BEFORE_TAX_YEAR_START,
	MTD_HMRC_ERR_RULE_CLASS4_OVER_16,
	MTD_HMRC_ERR_RULE_CLASS4_PENSION_AGE,
	MTD_HMRC_ERR_RULE_COMPLETION_DATE,
	MTD_HMRC_ERR_RULE_COMPLETION_DATE_BEFORE_DISPOSAL_DATE,
	MTD_HMRC_ERR_RULE_CONSOLIDATED_EXPENSES,
	MTD_HMRC_ERR_RULE_COST_OF_MATERIALS,
	MTD_HMRC_ERR_RULE_COUNTRY_CODE,
	MTD_HMRC_ERR_RULE_CUSTOM_EMPLOYMENT,
	MTD_HMRC_ERR_RULE_DATE_RANGE_INVALID,
	MTD_HMRC_ERR_RULE_DATE_RANGE_OUT_OF_DATE,
	MTD_HMRC_ERR_RULE_DECEASED_RECIPIENT,
	MTD_HMRC_ERR_RULE_DEDUCTIONS_AMOUNT,
	MTD_HMRC_ERR_RULE_DEDUCTIONS_DATE_RANGE_INVALID,
	MTD_HMRC_ERR_RULE_DELETE_AFTER_CRYSTALLISATION,
	MTD_HMRC_ERR_RULE_DELETE_FORBIDDEN,
	MTD_HMRC_ERR_RULE_DISPOSAL_DATE,
	MTD_HMRC_ERR_RULE_DUPLICATE_COUNTRY_CODE,
	MTD_HMRC_ERR_RULE_DUPLICATE_PERIOD,
	MTD_HMRC_ERR_RULE_DUPLICATE_SUBMISSION,
	MTD_HMRC_ERR_RULE_DUPLICATED_PPD_SUBMISSION_ID,
	MTD_HMRC_ERR_RULE_EARLY_SUBMISSION,
	MTD_HMRC_ERR_RULE_END_DATE_BEFORE_START_DATE,
	MTD_HMRC_ERR_RULE_END_DATE_BEFORE_TAX_YEAR_START,
	MTD_HMRC_ERR_RULE_FHL_PRIVATE_USE_ADJUSTMENT,
	MTD_HMRC_ERR_RULE_FINAL_DECLARATION_RECEIVED,
	MTD_HMRC_ERR_RULE_FROM_DATE_NOT_SUPPORTED,
	MTD_HMRC_ERR_RULE_GAIN_AFTER_RELIEF_LOSS_AFTER_RELIEF,
	MTD_HMRC_ERR_RULE_GAIN_LOSS,
	MTD_HMRC_ERR_RULE_GROSS_AMOUNT_PAID,
	MTD_HMRC_ERR_RULE_IGNORE_FORBIDDEN,
	MTD_HMRC_ERR_RULE_INCOME_SOURCES_CHANGED,
	MTD_HMRC_ERR_RULE_INCOME_SOURCES_INVALID,
	MTD_HMRC_ERR_RULE_INCORRECT_DISPOSAL_TYPE,
	MTD_HMRC_ERR_RULE_INCORRECT_OR_EMPTY_BODY_SUBMITTED,
	MTD_HMRC_ERR_RULE_INSOLVENT_TRADER,
	MTD_HMRC_ERR_RULE_INVALID_REQUEST,
	MTD_HMRC_ERR_RULE_INVALID_SEQUENCE_START,
	MTD_HMRC_ERR_RULE_IS_ANNUAL_ALLOWANCE_REDUCED,
	MTD_HMRC_ERR_RULE_LATE_SUBMISSION,
	MTD_HMRC_ERR_RULE_LOSS_AMOUNT,
	MTD_HMRC_ERR_RULE_LOSS_CLAIMS_MISSING,
	MTD_HMRC_ERR_RULE_LOSSES_GREATER_THAN_GAIN,
	MTD_HMRC_ERR_RULE_LUMP_SUMS,
	MTD_HMRC_ERR_RULE_MISALIGNED_PERIOD,
	MTD_HMRC_ERR_RULE_MISMATCHED_END_DATE,
	MTD_HMRC_ERR_RULE_MISMATCHED_START_DATE,
	MTD_HMRC_ERR_RULE_NO_ACCOUNTING_PERIOD,
	MTD_HMRC_ERR_RULE_NO_ADJUSTMENTS_MADE,
	MTD_HMRC_ERR_RULE_NO_CHANGE,
	MTD_HMRC_ERR_RULE_NO_INCOME_SUBMISSIONS_EXIST,
	MTD_HMRC_ERR_RULE_NO_SUBMISSIONS_EXIST,
	MTD_HMRC_ERR_RULE_NON_FHL_PRIVATE_USE_ADJUSTMENT,
	MTD_HMRC_ERR_RULE_NON_MATCHING_PERIOD,
	MTD_HMRC_ERR_RULE_NOT_CONTIGUOUS_PERIOD,
	MTD_HMRC_ERR_RULE_NOT_FINALISED,
	MTD_HMRC_ERR_RULE_NOT_FOREIGN_PROPERTY,
	MTD_HMRC_ERR_RULE_NOT_SELF_EMPLOYMENT,
	MTD_HMRC_ERR_RULE_NOT_UK_PROPERTY,
	MTD_HMRC_ERR_RULE_OVER_CONSOLIDATED_EXPENSES_THRESHOLD,
	MTD_HMRC_ERR_RULE_OVERLAPPING_PERIOD,
	MTD_HMRC_ERR_RULE_PERIOD_NOT_ENDED,
	MTD_HMRC_ERR_RULE_PERIODIC_DATA_INCOMPLETE,
	MTD_HMRC_ERR_RULE_PROPERTY_INCOME_ALLOWANCE,
	MTD_HMRC_ERR_RULE_PROPERTY_INCOME_ALLOWANCE_CLAIMED,
	MTD_HMRC_ERR_RULE_RANGE_INVALID,
	MTD_HMRC_ERR_RULE_RECENT_SUBMISSIONS_EXIST,
	MTD_HMRC_ERR_RULE_RESIDENCY_CHANGED,
	MTD_HMRC_ERR_RULE_RESULTING_VALUE_NOT_PERMITTED,
	MTD_HMRC_ERR_RULE_SELF_EMPLOYMENT_ADJUSTED,
	MTD_HMRC_ERR_RULE_SELF_EMPLOYMENT_ID,
	MTD_HMRC_ERR_RULE_SEQUENCE_ORDER_BROKEN,
	MTD_HMRC_ERR_RULE_SOURCE_INVALID,
	MTD_HMRC_ERR_RULE_START_DATE_AFTER_TAX_YEAR_END,
	MTD_HMRC_ERR_RULE_SUBMISSION_FAILED,
	MTD_HMRC_ERR_RULE_SUMMARY_STATUS_INVALID,
	MTD_HMRC_ERR_RULE_SUMMARY_STATUS_SUPERSEDED,
	MTD_HMRC_ERR_RULE_TAX_YEAR_NOT_ENDED,
	MTD_HMRC_ERR_RULE_TAX_YEAR_NOT_SUPPORTED,
	MTD_HMRC_ERR_RULE_TAX_YEAR_RANGE_INVALID,
	MTD_HMRC_ERR_RULE_TAX_YEAR_TOO_LONG,
	MTD_HMRC_ERR_RULE_TO_DATE_BEFORE_FROM_DATE,
	MTD_HMRC_ERR_RULE_TRADING_INCOME_ALLOWANCE_CLAIMED,
	MTD_HMRC_ERR_RULE_TYPE_OF_BUSINESS,
	MTD_HMRC_ERR_RULE_TYPE_OF_BUSINESS_INCORRECT,
	MTD_HMRC_ERR_RULE_TYPE_OF_CLAIM_INVALID,
	MTD_HMRC_ERR_RULE_UNALIGNED_DEDUCTIONS_PERIOD,
	MTD_HMRC_ERR_RULE_UNIGNORE_FORBIDDEN,
	MTD_HMRC_ERR_RULE_UPDATE_FORBIDDEN,
	MTD_HMRC_ERR_RULE_VOLUNTARY_CLASS2_CANNOT_BE_CHANGED,
	MTD_HMRC_ERR_RULE_VOLUNTARY_CLASS2_VALUE_INVALID,

	/*
	 * Self-Assessment API. This API is planned to be fully
	 * deprecated by March 2022. So group them altogether to
	 * facilitate easy removal.
	 */
	MTD_HMRC_ERR_SA_AGENT_NOT_AUTHORIZED,
	MTD_HMRC_ERR_SA_AGENT_NOT_SUBSCRIBED,
	MTD_HMRC_ERR_SA_BOTH_EXPENSES_SUPPLIED,
	MTD_HMRC_ERR_SA_CLIENT_NOT_SUBSCRIBED,
	MTD_HMRC_ERR_SA_DATE_NOT_IN_THE_PAST,
	MTD_HMRC_ERR_SA_FORMAT_ACCOUNT_NAME,
	MTD_HMRC_ERR_SA_FORMAT_GIFT_AID_FOLLOWING_YEAR_SPECIFIED_YEAR,
	MTD_HMRC_ERR_SA_FORMAT_GIFT_AID_NONUK_CHARITY_AMOUNT,
	MTD_HMRC_ERR_SA_FORMAT_GIFT_AID_NONUK_NAMES,
	MTD_HMRC_ERR_SA_FORMAT_GIFT_AID_ONE_OFF_SPECIFIED_YEAR,
	MTD_HMRC_ERR_SA_FORMAT_GIFT_AID_SPECIFIED_YEAR,
	MTD_HMRC_ERR_SA_FORMAT_GIFT_AID_SPECIFIED_YEAR_PREVIOUS_YEAR,
	MTD_HMRC_ERR_SA_FORMAT_GIFTS_INVESTMENTS_AMOUNT,
	MTD_HMRC_ERR_SA_FORMAT_GIFTS_LAND_BUILDINGS,
	MTD_HMRC_ERR_SA_FORMAT_GIFTS_NONUK_INVESTMENTS_NAMES,
	MTD_HMRC_ERR_SA_FORMAT_GIFTS_SHARES_SECURITIES,
	MTD_HMRC_ERR_SA_FORMAT_OTHER_DIVIDENDS,
	MTD_HMRC_ERR_SA_FORMAT_SAVINGS_ACCOUNT_ID,
	MTD_HMRC_ERR_SA_FORMAT_TAXED_INTEREST,
	MTD_HMRC_ERR_SA_FORMAT_UK_DIVIDENDS,
	MTD_HMRC_ERR_SA_FORMAT_UNTAXED_INTEREST,
	MTD_HMRC_ERR_SA_INVALID_ACCOUNTING_PERIOD,
	MTD_HMRC_ERR_SA_INVALID_BOOLEAN_VALUE,
	MTD_HMRC_ERR_SA_INVALID_DATE,
	MTD_HMRC_ERR_SA_INVALID_FIELD_FORMAT,
	MTD_HMRC_ERR_SA_INVALID_FIELD_LENGTH,
	MTD_HMRC_ERR_SA_INVALID_MONETARY_AMOUNT,
	MTD_HMRC_ERR_SA_INVALID_PERIOD,
	MTD_HMRC_ERR_SA_INVALID_POSTCODE,
	MTD_HMRC_ERR_SA_INVALID_VALUE,
	MTD_HMRC_ERR_SA_MANDATORY_FIELD_MISSING,
	MTD_HMRC_ERR_SA_MISALIGNED_PERIOD,
	MTD_HMRC_ERR_SA_MISSING_ACCOUNT_NAME,
	MTD_HMRC_ERR_SA_NINO_INVALID,
	MTD_HMRC_ERR_SA_NO_INCOMES_AND_EXPENSES,
	MTD_HMRC_ERR_SA_NOT_ALLOWED_CONSOLIDATED_EXPENSES,
	MTD_HMRC_ERR_SA_NOT_CONTIGUOUS_PERIOD,
	MTD_HMRC_ERR_SA_NOT_OVER_STATE_PENSION,
	MTD_HMRC_ERR_SA_NOT_UNDER_16,
	MTD_HMRC_ERR_SA_OVERLAPPING_PERIOD,
	MTD_HMRC_ERR_SA_RULE_DUPLICATE_ACCOUNT_NAME,
	MTD_HMRC_ERR_SA_RULE_EMPTY_GIFTS_OR_GIFT_AID,
	MTD_HMRC_ERR_SA_RULE_GIFT_AID_NONUK_AMOUNT_WITHOUT_NAMES,
	MTD_HMRC_ERR_SA_RULE_GIFT_AID_NONUK_NAMES_WITHOUT_AMOUNT,
	MTD_HMRC_ERR_SA_RULE_GIFTS_NONUK_INVESTMENTS_AMOUNT_WITHOUT_NAMES,
	MTD_HMRC_ERR_SA_RULE_GIFTS_NONUK_INVESTMENTS_NAMES_WITHOUT_AMOUNT,
	MTD_HMRC_ERR_SA_RULE_MAXIMUM_SAVINGS_ACCOUNTS_LIMIT,
	MTD_HMRC_ERR_SA_RULE_TAX_YEAR_RANGE_EXCEEDED,
	MTD_HMRC_ERR_SA_START_DATE_INVALID,
	MTD_HMRC_ERR_SA_TAX_YEAR_INVALID,

	/* Generic top-level errors */
	MTD_HMRC_ERR_BUSINESS_ERROR,
	MTD_HMRC_ERR_INVALID_REQUEST,

	/* keep this last */
	MTD_HMRC_ERR_UNKNOWN
};

/* Just the HTTP status codes relevant to the MTD API */
enum mtd_http_status_code {
	MTD_HTTP_OK = 200,
	MTD_HTTP_CREATED,
	MTD_HTTP_ACCEPTED,
	MTD_HTTP_NO_CONTENT = 204,
	MTD_HTTP_SEE_OTHER = 303,
	MTD_HTTP_BAD_REQUEST = 400,
	MTD_HTTP_UNAUTHORIZED,
	MTD_HTTP_FORBIDDEN = 403,
	MTD_HTTP_NOT_FOUND,
	MTD_HTTP_METHOD_NOT_ALLOWED,
	MTD_HTTP_NOT_ACCEPTABLE,
	MTD_HTTP_GONE = 410,
	MTD_HTTP_REQUEST_ENTITY_TOO_LARGE = 413,
	MTD_HTTP_UNSUPPORTED_MEDIA_TYPE = 415,
	MTD_HTTP_TOO_MANY_REQUESTS = 429,
	MTD_HTTP_INTERNAL_SERVER_ERROR = 500,
	MTD_HTTP_NOT_IMPLEMENTED,
	MTD_HTTP_SERVICE_UNAVAILABLE = 503,
	MTD_HTTP_GATEWAY_TIMEOUT,
};

enum mtd_scope {
	MTD_SCOPE_RD_SA		= 0x1,
	MTD_SCOPE_WR_SA		= 0x2,
	MTD_SCOPE_RD_VAT	= 0x4,
	MTD_SCOPE_WR_VAT	= 0x8,
};

enum mtd_ep_api {
	MTD_EP_API_ITSA = 0,
	MTD_EP_API_VAT,

	/*
	 * Special value to tell we are adding more API
	 * OAuths and _not_ to reset the oauth.json file.
	 *
	 * This can be bitwise OR'd with any of the above.
	 */
	MTD_EP_API_ADD = (1 << 29),

	/* Only used internally */
	MTD_EP_API_NULL = (1 << 30)
};

enum mtd_data_src_type {
	MTD_DATA_SRC_FILE = 0,
	MTD_DATA_SRC_BUF,
	MTD_DATA_SRC_FP,
	MTD_DATA_SRC_FD,
};

typedef union mtd_data_src {
	const void *buf;
	const char *file;
	FILE *fp;
	int fd;
} mtd_data_src_t;

struct mtd_dsrc_ctx {
	mtd_data_src_t data_src;
	size_t data_len;

	enum mtd_data_src_type src_type;
};

#define MTD_FPH_SET_FUNC(s, m, f)	s.m = f

#define MTD_FPH_CLI_PUBLIC_IP			fph_srcip
#define MTD_FPH_CLI_PUBLIC_PORT			fph_srcport
#define MTD_FPH_CLI_DEV_ID			fph_device_id
#define MTD_FPH_CLI_USER_ID			fph_user
#define MTD_FPH_CLI_TZ				fph_tz
#define MTD_FPH_CLI_LOCAL_IPS			fph_ipaddrs
#define MTD_FPH_CLI_MAC_ADDRS			fph_macaddrs
#define MTD_FPH_CLI_UA				fph_ua
#define MTD_FPH_CLI_MULTI_FACTOR		fph_multi_factor
#define MTD_FPH_CLI_SCREENS			fph_screens
#define MTD_FPH_CLI_WINDOW_SZ			fph_window_sz
#define MTD_FPH_CLI_BROWSER_PLUGINS		fph_browser_plugins
#define MTD_FPH_CLI_BROWSER_JS_UA		fph_browser_js_ua
#define MTD_FPH_CLI_BROWSER_DNT			fph_browser_dnt
#define MTD_FPH_CLI_LOCAL_IPS_TS		fph_ipaddrs_ts
#define MTD_FPH_CLI_PUBLIC_IP_TS		fph_srcip_ts
#define MTD_FPH_VEN_VERSION			fph_version
#define MTD_FPH_VEN_VERSION_CLI			fph_version_cli
#define MTD_FPH_VEN_LICENSE_ID			fph_license_id
#define MTD_FPH_VEN_PUBLIC_IP			fph_vendor_ip
#define MTD_FPH_VEN_FWD				fph_vendor_fwd
#define MTD_FPH_VEN_PROD_NAME			fph_prod_name

struct mtd_fph_ops {
	char *(*fph_device_id)(void *user_data);
	char *(*fph_user)(void *user_data);
	char *(*fph_tz)(void *user_data);
	char *(*fph_ipaddrs)(void *user_data);
	char *(*fph_ipaddrs_ts)(void *user_data);
	char *(*fph_macaddrs)(void *user_data);
	char *(*fph_srcip)(void *user_data);
	char *(*fph_srcip_ts)(void *user_data);
	char *(*fph_srcport)(void *user_data);
	char *(*fph_screens)(void *user_data);
	char *(*fph_window_sz)(void *user_data);
	char *(*fph_browser_plugins)(void *user_data);
	char *(*fph_browser_js_ua)(void *user_data);
	char *(*fph_browser_dnt)(void *user_data);
	char *(*fph_vendor_ip)(void *user_data);
	char *(*fph_vendor_fwd)(void *user_data);
	char *(*fph_ua)(void *user_data);
	char *(*fph_multi_factor)(void *user_data);
	char *(*fph_license_id)(void *user_data);
	char *(*fph_version)(void *user_data);
	char *(*fph_version_cli)(void *user_data);
	char *(*fph_prod_name)(void *user_data);

	void *user_data;
};

struct mtd_cfg {
	const struct mtd_fph_ops *fph_ops;
	const char * const *extra_hdrs;

	const char *config_dir;
};

#pragma GCC visibility push(default)

extern void mtd_global_init(void);
extern int mtd_init(unsigned int flags, const struct mtd_cfg *cfg);
extern void mtd_deinit(void);
extern int mtd_init_auth(enum mtd_ep_api api, unsigned long scopes);
extern int mtd_init_creds(enum mtd_ep_api api);
extern int mtd_init_nino(void);
extern char *mtd_percent_encode(const char *str, ssize_t len);
extern const char *mtd_err2str(int err);
extern const char *mtd_err2enum_str(int err);
extern enum mtd_http_status_code mtd_http_status_code(const char *json);
extern const char *mtd_http_status_str_u(const char *json);
extern const char *mtd_http_status_str(const char *json);
extern enum mtd_hmrc_error mtd_hmrc_error(const char *json);

#pragma GCC visibility pop

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* _MTD_H_ */
