language: c

os: linux
dist: trusty

git:
  depth: false

before_install:
  - wget https://github.com/akheron/jansson/releases/download/v2.13.1/jansson-2.13.1.tar.bz2
  - tar -xf jansson-2.13.1.tar.bz2
  - cd jansson-2.13.1
  - ./configure && make -j2
  - sudo make install
  - cd ..

jobs:
  include:
    - os: linux
      dist: trusty
      script: make V=1
    - os: linux
      dist: focal
      addons:
        apt:
          sources:
            - sourceline: ppa:ubuntu-toolchain-r/test
          packages:
            - gcc-11
      script: make CC=gcc-11 V=1
    - os: freebsd
      addons:
        pkg:
          - jansson
          - e2fsprogs-libuuid
      before_install:
      script: gmake CC=clang V=1
