.TH libmtdac_mtd-test-cu.h 3 "June 1, 2020" "libmtdac 0.9.0" "libmtdac_mtd-test-cu.h"

.SH NAME
libmtdac_mtd-test-cu.h \- Make Tax Digital \- Create Test User API

.SH SYNOPSIS
.B #include <libmtdac/mtd-test-cu.h>

.SH DESCRIPTION
These functions are for working with the UK's HMRC Make Tax Digital Create
Test User API.

.SH FUNCTIONS

.nf
.BI "int mtd_test_cu_create_individual(const char *" src_file ", char **" buf ");"

.RS +4
.BR mtd_test_cu_create_individual (3)
.RE

.BI "int mtd_test_cu_create_organisation(const char *" src_file ", char **" buf ");"

.RS +4
.BR mtd_test_cu_create_organisation (3)
.RE

.BI "int mtd_test_cu_create_agent(const char *" src_file ", char **" buf ");"

.RS +4
.BR mtd_test_cu_create_agent (3)
.RE

.BI "int mtd_test_cu_list_services(char **" buf ");"

.RS +4
.BR mtd_test_cu_list_services (3)
.RE
.fi

.SH SEE ALSO

.BR libmtdac (3),
.BR libmtdac_mtd.h (3)
