.TH libmtdac_mtd-test-ni.h 3 "June 1, 2020" "libmtdac 0.9.0" "libmtdac_mtd-test-ni.h"

.SH NAME
libmtdac_mtd-test-ni.h \- Make Tax Digital \- National Insurance Test Support API

.SH SYNOPSIS
.B #include <libmtdac/mtd-test-ni.h>

.SH DESCRIPTION
These functions are for working with the UK's HMRC Make Tax Digital National
Insurance Test Support API.

.SH FUNCTIONS

.nf
.BI "int mtd_test_ni_create_annual_summary(const char *" src_file ",
.BI "                                      const char *" utr ",
.BI "                                      const char *" tax_year ",
.BI "                                      char **" buf ");"

.RS +4
.BR mtd_test_ni_create_annual_summary (3)
.RE
.ni

.SH SEE ALSO

.BR libmtdac (3),
.BR libmtdac_mtd.h (3)
