.TH libmtdac_mtd-test-fph.h 3 "August 3, 2021" "libmtdac 0.50.0" "libmtdac_mtd-test-fph.h"

.SH NAME
libmtdac_mtd-test-fph.h \- Make Tax Digital \- Test Fraud Prevention Headers
API

.SH SYNOPSIS
.B #include <libmtdac/mtd-test-fph.h>

.SH DESCRIPTION
These functions are for working with the UK's HMRC Make Tax Digital Test Fraud
Prevention Headers API.

.SH FUNCTIONS

.nf
.BI "int mtd_test_fph_validate(char **" buf ");"

.RS +4
.BR mtd_test_fph_validate (3)
.RE

.BI "int mtd_test_fph_feedback(const char *" api ", const char *" query_string ",
.BI "                          char **" buf ");

.RS +4
.BR mtd_test_fph_feedback (3)
.RE
.fi

.SH SEE ALSO

.BR libmtdac (3),
.BR libmtdac_mtd.h (3)
