.TH libmtdac_mtd-test-fph.h 3 "June 1, 2020" "libmtdac 0.9.0" "libmtdac_mtd-test-fph.h"

.SH NAME
libmtdac_mtd-test-fph.h \- Make Tax Digital \- Test Fraud Prevention Headers
API

.SH SYNOPSIS
.B #include <libmtdac/mtd-test-fph.h>

.SH DESCRIPTION
These functions are for working with the UK's HMRC Make Tax Digital Test Fraud
Prevention Headers API.

.SH FUNCTIONS

.nf
.BI "int mtd_test_fph_validate(char **" buf ");"

.RS +4
.BR mtd_test_fph_validate (3)
.RE
.ni

.SH SEE ALSO

.BR libmtdac (3),
.BR libmtdac_mtd.h (3)
