.TH libmtdac_mtd-il.h 3 "June 1, 2020" "libmtdac 0.9.0" "libmtdac_mtd-il.h"

.SH NAME
libmtdac_mtd-il.h \- Make Tax Digital \- Individual Loses API

.SH SYNOPSIS
.B #include <libmtdac/mtd-il.h>

.SH DESCRIPTION
These functions are for working with the UK's HMRC Make Tax Digital
Individual Loses API.

.SH FUNCTIONS

.SS Brought Forward Losses

.nf
.BI "int mtd_il_bf_list_loses(const char *" query_string ", char **" buf ");"

.RS +4
.BR mtd_il_bf_list_loses (3)
.RE

.BI "int mtd_il_bf_create_loss(const char *" src_file ", char **" buf ");"

.RS +4
.BR mtd_il_bf_create_loss (3)
.RE

.BI "int mtd_il_bf_get_loss(const char *" lid ", char **" buf ");"

.RS +4
.BR mtd_il_bf_get_loss (3)
.RE

.BI "int mtd_il_bf_delete_loss(const char *" lid ", char **" buf ");

.RS +4
.BR mtd_il_bf_delete_loss (3)
.RE

.BI "int mtd_il_bf_update_loss_amnt(const char *" src_file ", const char *" lid ",
.BI "                               char **" buf ");"

.RS +4
.BR mtd_il_bf_update_loss_amnt (3)
.RE
.fi

.SS Loss Claims

.nf
.BI "int mtd_il_lc_list_loses(const char *" query_string ", char **" buf ");"

.RS +4
.BR mtd_il_lc_list_loses (3)
.RE

.BI "int mtd_il_lc_create_loss(const char *" src_file ", char **" buf ");"

.RS +4
.BR mtd_il_lc_create_loss (3)
.RE

.BI "int mtd_il_lc_get_loss(const char *" cid ", char **" buf ");"

.RS +4
.BR mtd_il_lc_get_loss (3)
.RE

.BI "int mtd_il_lc_delete_loss(const char *" cid ", char **" buf ");"

.RS +4
.BR mtd_il_lc_delete_loss (3)
.RE

.BI "int mtd_il_lc_update_loss_type(const char *" src_file ", const char *" cid ",
.BI "                               char **" buf ");"

.RS +4
.BR mtd_il_lc_update_loss_type (3)
.RE

.BI "int mtd_il_lc_update_loss_order(const char *" src_file ", char **" buf ");"

.RS +4
.BR mtd_il_lc_update_loss_order (3)
.RE
.fi

.SH SEE ALSO

.BR libmtdac (3),
.BR libmtdac_mtd.h (3)
