.TH libmtdac_mtd-bd.h 3 "July 9, 2021" "libmtdac 0.50.0" "libmtdac_mtd-bd.h"

.SH NAME
libmtdac_mtd-bd.h \- Make Tax Digital \- Business Details API

.SH SYNOPSIS
.B #include <libmtdac/mtd-bd.h>

.SH DESCRIPTION
These functions are for working with the UK's HMRC Make Tax Digital Business
Details API.

.SH FUNCTIONS

.nf
.BI "int mtd_bd_list(char **" buf );

.RS +4
.BR mtd_bd_list (3)
.RE

.BI "int mtd_bd_get(const char *" bid ", char **" buf );

.RS +4
.BR mtd_bd_get (3)
.RE
.fi

.SH SEE ALSO

.BR libmtdac (3),
.BR libmtdac_mtd.h (3)
