.TH libmtdac_mtd-bsas.h 3 "August 8, 2021" "libmtdac 0.50.0" "libmtdac_mtd-bsas.h"

.SH NAME
libmtdac_mtd-bsas.h \- Make Tax Digital \- Business Source Adjustable Summary API

.SH SYNOPSIS
.B #include <libmtdac/mtd-bsas.h>

.SH DESCRIPTION
These functions are for working with the UK's HMRC Make Tax Digital Business
Source Adjustable Summary API.

.SH FUNCTIONS

.nf
.BI "int mtd_bsas_list_summaries(const char *" query_string ", char **" buf ");"

.RS +4
.BR mtd_bsas_list_summaries (3)
.RE

.BI "int mtd_bsas_trigger_summary(const char *" src_file ", char **" buf ");"

.RS +4
.BR mtd_bsas_trigger_summary (3)
.RE
.fi

.SS Self-Employment

.nf
.BI "int mtd_bsas_se_get_summary(const char *" bid ", const char *" query_string ",
.BI "                            char **" buf ");"

.RS +4
.BR mtd_bsas_se_get_summary (3)
.RE

.BI "int mtd_bsas_se_list_summary_adjustments(const char *" bid ", char **" buf ");"

.RS +4
.BR mtd_bsas_se_list_summary_adjustments (3)
.RE

.BI "int mtd_bsas_se_update_summary_adjustments(const char *" src_file ",
.BI "                                           const char *" bid ", char **" buf ");"

.RS +4
.BR mtd_bsas_se_update_summary_adjustments (3)
.RE
.fi

.SS UK Property Business

.nf
.BI "int mtd_bsas_pb_get_summary(const char *" bid ", const char *" query_string ",
.BI "                            char **" buf ");"

.RS +4
.BR mtd_bsas_pb_get_summary (3)
.RE

.BI "int mtd_bsas_pb_list_summary_adjustments(const char *" bid ", char **" buf ");"

.RS +4
.BR mtd_bsas_pb_list_summary_adjustments (3)
.RE

.BI "int mtd_bsas_pb_update_summary_adjustments(const char *" src_file ",
.BI "                                           const char *" bid ", char **" buf ");"

.RS +4
.BR mtd_bsas_pb_update_summary_adjustments (3)
.RE
.fi

.SS Foreign Property Business

.nf
.BI "int mtd_bsas_fp_get_summary(const char *" bid ", const char *" query_string ",
.BI "                            char **" buf ");"

.RS +4
.BR mtd_bsas_fp_get_summary (3)
.RE

.BI "int mtd_bsas_fp_list_summary_adjustments(const char *" bid ", char **" buf ");"

.RS +4
.BR mtd_bsas_fp_list_summary_adjustments (3)
.RE

.BI "int mtd_bsas_fp_update_summary_adjustments(const char *" src_file ",
.BI "                                           const char *" bid ", char **" buf ");"

.RS +4
.BR mtd_bsas_fp_update_summary_adjustments (3)
.RE
.fi
.SH SEE ALSO

.BR libmtdac (3),
.BR libmtdac_mtd.h (3)
