.TH libmtdac 3 "June 1, 2020" "libmtdac 0.9.0" "libmtdac overview"

.SH NAME
libmtdac \- UK HMRC Make Tax Digital API interface

.SH DESCRIPTION
This is a C library for interacting with the UK's HMRC Make Tax Digital API.

This man page provides a general overview while there are dedicated man pages
for each function, types & defines etc.

.SH SYNOPSIS
Main types / defines / functions

.RS +4
.BR libmtdac_mtd.h (3)
.RE

Endpoint API's. This currently supports the following Endpoint API's

Self Assessment (MTD) API

.RS +4
.BR libmtdac_mtd-sa.h (3)
.RE

Self Assessment Accounts (MTD) API

.RS +4
.BR libmtdac_mtd-saac.h (3)
.RE

Individual Calculations (MTD) API

.RS +4
.BR libmtdac_mtd-ic.h (3)
.RE

Individual Losses (MTD) API

.RS +4
.BR libmtdac_mtd-il.h (3)
.RE

Individual Employment (MTD) API

.RS +4
.BR libmtdac_mtd-ie.h (3)
.RE

Individual Income (MTD) API

.RS +4
.BR libmtdac_mtd-ii.h (3)
.RE

Business Income Source Summary (MTD) API

.RS +4
.BR libmtdac_mtd-biss.h (3)
.RE

National Insurance API

.RS +4
.BR libmtdac_mtd-ni.h (3)
.RE

Create Test User API

.RS +4
.BR libmtdac_mtd-test-cu.h (3)
.RE

National Insurance Test Support API

.RS +4
.BR libmtdac_mtd-test-ni.h (3)
.RE

Test Fraud Prevention Headers API

.RS +4
.BR libmtdac_mtd-test-fph.h (3)
.RE

.PP

Each of the above is an overview man page, there are individual function man
pages also.
.PP
When reading the individual man pages, you will sometimes see a
\fBquery_string\fP argument. Sometimes this is optional or some parts of it
may be optional.
.PP
The optional parts will be enclosed in \fB[]\fP.
.PP
You make also see bits enclosed in \fB{}\fP that show a set of choices where
you should choose \fBone\fP.

.SH USING
Include one or more of the above headers in your program and link with
\fB-lmtdac\fP

.SH THREAD SAFETY
libmtdac should not at least be inherently thread unsafe.

.SH LICENSE
libmtdac is licensed under the GNU Lesser General Public License (LGPL) version 2.1

.SH SOURCE
Source available at https://github.com/ac000/libmtdac

.SH AUTHOR
Andrew Clayton <andrew@digital-domain.net>

