.TH libmtdac_mtd-biss.h 3 "February 2, 2021" "libmtdac 0.18.0" "libmtdac_mtd-biss.h"

.SH NAME
libmtdac_mtd-biss.h \- Make Tax Digital \- Business Income Source Summary API

.SH SYNOPSIS
.B #include <libmtdac/mtd-biss.h>

.SH DESCRIPTION
These functions are for working with the UK's HMRC Make Tax Digital
Business Income Source Summary API.

.SH FUNCTIONS

.nf
.BI "int mtd_biss_get_self_employment(const char *" query_string ", char **" buf ");"

.RS +4
.BR mtd_biss_get_self_employment (3)
.RE

.BI "int mtd_biss_get_uk_property(const char *" query_string ", char **" buf ");"

.RS +4
.BR mtd_biss_get_uk_property (3)
.RE

.BI "int mtd_biss_get_foreign_property(const char *" query_string ", char **" buf ");

.RS +4
.BR mtd_biss_get_foreign_property (3)
.RE
.ni

.SH SEE ALSO

.BR libmtdac (3),
.BR libmtdac_mtd.h (3)
