.TH libmtdac_mtd-ic.h 3 "July 29, 2022" "libmtdac 0.61.0" "libmtdac_mtd-ic.h"

.SH NAME
libmtdac_mtd-ic.h \- Make Tax Digital \- Individual Calculations API 3.0

.SH SYNOPSIS
.B #include <libmtdac/mtd-ic.h>

.SH DESCRIPTION
These functions are for working with the UK's HMRC Make Tax Digital
Individual Calculations API.

.SH FUNCTIONS

.SS TAX Calculations

.nf
.BI "int mtd_ic_list_calculations(const char *" query_string ", char **" buf ");"

.RS +4
.BR mtd_ic_list_calculations (3)
.RE

.BI "int mtd_ic_trigger_calculation(const char *" tax_year ",
.BI "                               const char *" query_string ", char **" buf );

.RS +4
.BR mtd_ic_trigger_calculation (3)
.RE

.BI "int mtd_ic_get_calculation(const char *" tax_year ", const char *" cid ,
.BI "                           char **" buf );

.RS +4
.BR mtd_ic_get_calculation (3)
.RE
.RE
.fi

.SS Final Declaration

.nf
.BI "int mtd_ic_final_decl(const char *" cid ", char **" buf );

.RS +4
.BR mtd_ic_final_decl (3)
.RE
.fi

.SH SEE ALSO

.BR libmtdac (3),
.BR libmtdac_mtd.h (3)

.PP
HMRC documentation for this API can be found at
.PP

.in +4
.nf
.B https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/individual-calculations-api/3.0
