.TH libmtdac_mtd-ni.h 3 "June 1, 2020" "libmtdac 0.9.0" "libmtdac_mtd-ni.h"

.SH NAME
libmtdac_mtd-ni.h \- Make Tax Digital \- National Insurance API

.SH SYNOPSIS
.B #include <libmtdac/mtd-ni.h>

.SH DESCRIPTION
These functions are for working with the UK's HMRC Make Tax Digital
National Insurance API.

.SH FUNCTIONS

.nf
.BI "int mtd_ni_get_annual_summary(const char *" utr ", const char *" tax_year ",
.BI "                              char **" buf ");"

.RS +4
.BR mtd_ni_get_annual_summary (3)
.RE
.ni

.SH SEE ALSO

.BR libmtdac (3),
.BR libmtdac_mtd.h (3)
