.TH libmtdac_mtd-vat.h 3 "September 24, 2020" "libmtdac 0.16.0" "libmtdac_mtd-vat.h"

.SH NAME
libmtdac_mtd-vat.h \- Make Tax Digital \- VAT API

.SH SYNOPSIS
.B #include <libmtdac/mtd-vat.h>

.SH DESCRIPTION
These functions are for working with the UK's HMRC Make Tax Digital VAT API.

.SH FUNCTIONS

.nf
.BI "int mtd_vat_list_obligations(const char *" vrn ", const char *" query_string ",
.BI "                             char **" buf );

.RS +4
.BR mtd_vat_list_obligations (3)
.RE

.BI "int mtd_vat_submit_period(const struct mtd_dsrc_ctx *" dsctx ",
.BI "                          const char *" vrn ", char **" buf );

.RS +4
.BR mtd_vat_submit_period (3)
.RE

.BI "int mtd_vat_get_period(const char *" vrn ", const char *" period_key ",
.BI "                       char **" buf );

.RS +4
.BR mtd_vat_get_period (3)
.RE

.BI "int mtd_vat_list_liabilities(const char *" vrn ", const char *" query_string ",
.BI "                             char **" buf );

.RS +4
.BR mtd_vat_list_liabilities (3)
.RE

.BI "int mtd_vat_list_payments(const char *" vrn ", const char *" query_string ",
.BI "                          char **" buf );

.RS +4
.BR mtd_vat_list_payments (3)
.RE

.SH SEE ALSO

.BR libmtdac (3),
.BR libmtdac_mtd.h (3)
