.TH libmtdac_mtd-biss.h 3 "April 2, 2022" "libmtdac 0.60.0" "libmtdac_mtd-biss.h"

.SH NAME
libmtdac_mtd-biss.h \- Make Tax Digital \- Business Income Source Summary API

.SH SYNOPSIS
.B #include <libmtdac/mtd-biss.h>

.SH DESCRIPTION
These functions are for working with the UK's HMRC Make Tax Digital
Business Income Source Summary API.

.SH FUNCTIONS

.nf
.BI "int mtd_biss_get_summary(const char *" business_type ",
.BI "                         const char *" tax_year ", const char *" bid ",
.BI "                         char **" buf ");

.RS +4
.BR mtd_biss_get_summary (3)
.RE
.fi

.SH SEE ALSO

.BR libmtdac (3),
.BR libmtdac_mtd.h (3)
