.TH libmtdac_mtd-ibeops.h 3 "August 23, 2021" "libmtdac 0.50.0" "libmtdac_mtd-ibeops.h"

.SH NAME
libmtdac_mtd-ibeops.h \- Make Tax Digital \- Individuals Business End of Period Statement API

.SH SYNOPSIS
.B #include <libmtdac/mtd-ibeops.h>

.SH DESCRIPTION
This API allows a developer to submit a declaration that the submission date
for a business is complete.

.SH FUNCTIONS

.nf
.BI "int mtd_ibeops_submit_eops(const struct mtd_dsrc_ctx *" dsctx ",
.BI "                           char **" buf ");

.RS +4
.BR mtd_ibeops_submit_eops (3)
.RE

.SH SEE ALSO

.BR libmtdac (3),
.BR libmtdac_mtd.h (3)
