.TH MTD_IBEOPS_SUBMIT_EOPS 3 "August 23, 2021" "" "libmtdac"

.SH NAME

mtd_ibeops_submit_eops \- finalise an end-of-period statement

.SH SYNOPSIS

.B #include <libmtdac/mtd-ibeops.h>
.PP
.nf
.BI "int mtd_ibeops_submit_eops(const struct mtd_dsrc_ctx *" dsctx ",
.BI "                           char **" buf );
.fi

.SH DESCRIPTION

This function allows the developer to submit a declaration that the submission
data for a given business is complete.

.TP 4
.B dsctx
This points to either a buffer, filename, file pointer or file descriptor that
contains the JSON payload to be sent. See
.BR mtd_dsrc_ctx (3).
The JSON should look like
.PP
.RS 8
.EX
{
    "typeOfBusiness": "self-employment",
    "businessId": "XAIS12345678910",
    "accountingPeriod" : {
        "startDate": "2021-04-06",
        "endDate": "2022-04-05"
    },
    "finalised": true
}
.EE
.RE

.TP
.B buf
.RS 4
This is the result buffer containing the JSON result string. It should be
\fBfree(3)\fP'd when no longer needed.
.RE

.SH RETURN VALUE

On success, zero (\fBMTD_ERR_NONE\fP) is returned. On error, a negative error
code is returned.

.SH ERRORS

.TP
.B -MTD_ERR_OS
There was an OS level failure

.TP 4
.B -MTD_ERR_REQUEST
The API request returned a status code >= 300

.TP
.B -MTD_ERR_CURL
There was a problem with the curl request itself

.SH SEE ALSO

.BR libmtdac (3),
.BR libmtdac_mtd.h (3),
.BR mtd_dsrc_ctx (3),
.BR libmtdac-result_buffer (3)
