.TH MTD_SA_SE_LIST_OBLIGATIONS 3 "September 9, 2020" "" "libmtdac"

.SH NAME

mtd_sa_se_list_obligations \- retrieve self-employment business obligations

.SH SYNOPSIS

.B #include <libmtdac/mtd-sa.h>
.PP
.nf
.BI "int mtd_sa_se_list_obligations(const char *" seid ",
.BI "                               const char *" query_string ", char **" buf );
.ni

.SH DESCRIPTION

This function allows a developer to retrieve self-employment business
obligations for a specific business, (see \fBseid\fP below).

.TP 4
.B seid
This is the selfEmploymentId and is in the form
.PP
.RS 8
^X[A-Z0-9]{1}IS[0-9]{11}$
.RE

.TP 4
.B query_string
This is optional and is in the form
.PP
.RS 8
\fB?[from=YYYY-MM-DD][&[to=YYYY-MM-DD]]\fP
.RE

.TP
.B buf
.RS 4
This is the result buffer containing the JSON result string. It should be
\fBfree(3)\fP'd when no longer needed.
.RE

.SH RETURN VALUE

On success, zero (\fBMTD_ERR_NONE\fP) is returned. On error, a positive error
code is returned.

.SH ERRORS

.TP 4
.B MTD_ERR_REQUEST
The API request returned a status code >= 300

.TP
.B MTD_ERR_CURL
There was a problem with the curl request itself

.TP
.B MTD_ERR_OS
There was an OS level failure

.SH SEE ALSO

.BR libmtdac (3),
.BR libmtdac_mtd.h (3),
.BR libmtdac-result_buffer (3)
