.TH MTD_HMRC_ERROR 3 "March 17, 2021" "" "libmtdac"

.SH NAME

mtd_hmrc_error \- get hmrc endpoint error code

.SH SYNOPSIS

.B #include <libmtdac/mtd.h>
.PP
.BI "enum mtd_hmrc_error mtd_hmrc_error(const char *" json );

.SH DESCRIPTION

This function given a JSON request result buffer will return the HMRC MTD
endpoint error code of the last request contained in the buffer.

.TP 3
.B json
A JSON result buffer as returned by the mtd_* functions.

.SH RETURN VALUE

An enum value corresponding to the HMRC MTD endpoint error code.

.SH SEE ALSO

.BR libmtdac (3),
.BR libmtdac_mtd.h (3)
