.TH MTD_VAT_GET_PERIOD 3 "September 24, 2020" "" "libmtdac"

.SH NAME

mtd_vat_get_period \- retrieve a submitted VAT return

.SH SYNOPSIS

.B #include <libmtdac/mtd-vat.h>
.PP
.nf
.BI "int mtd_vat_get_period(const char *" vrn ", const char *" period_key ",
.BI "                       char **" buf );
.ni

.SH DESCRIPTION

This function allows a developer to retrieve details about a previously
submitted VAT return.

.TP 3
.B vrn
This is the 9-digit VAT registration number and is in the form
.PP
.RS 8
^[0-9]{9}$
.RE

.TP 4
.B period_key
The ID code for the period that this obligation belongs to and is of the form
.PP
.RS 8
^[0-9#][0-9]{3}$
.RE

.TP
.B buf
.RS 4
This is the result buffer containing the JSON result string. It should be
\fBfree(3)\fP'd when no longer needed.
.RE

.SH RETURN VALUE

On success, zero (\fBMTD_ERR_NONE\fP) is returned. On error, a negative error
code is returned.

.SH ERRORS

.TP
.B -MTD_ERR_OS
There was an OS level failure

.TP 4
.B -MTD_ERR_REQUEST
The API request returned a status code >= 300

.TP
.B -MTD_ERR_CURL
There was a problem with the curl request itself

.SH SEE ALSO

.BR libmtdac (3),
.BR libmtdac_mtd.h (3),
.BR libmtdac-result_buffer (3)
