.TH MTD_HDRS_RESET 3 "June 11, 2020" "" "libmtdac"

.SH NAME

mtd_hdrs_reset \- clear any extra HTTP headers that were set

.SH SYNOPSIS

.B #include <libmtdac/mtd.h>
.PP
.BI "void mtd_hdrs_reset(void);"

.SH DESCRIPTION

This function can be used to clear any extra HTTP headers that were set with
.BR mtd_hdrs_add (3)

.SH ERRORS

None. This function always succeeds.

.SH SEE ALSO

.BR libmtdac (3),
.BR libmtdac_mtd.h (3),
.BR mtd_hdrs_add (3)
