.TH MTD_BSAS_SE_UPDATE_SUMMARY_ADJUSTMENTS 3 "Mar 27, 2022" "" "libmtdac"

.SH NAME

mtd_bsas_se_update_summary_adjustments \- update a self-employment Business
Source Adjustable Summary

.SH SYNOPSIS

.B #include <libmtdac/mtd-bsas.h>
.PP
.nf
.BI "int mtd_bsas_se_update_summary_adjustments(const struct mtd_dsrc_ctx *" dsctx ",
.BI "                                           const char *" cid ", char **" buf );
.fi

.SH DESCRIPTION

This function is part of the UK's HMRC Make Tax Digital Business Source
Adjustable Summaries API.
.PP
This function allows a developer to provide accounting adjustments against a
specified Business Source Accounting Summary via its \fBcalculationID\fP which
must be for a Self-Employment Business and it must not have been adjusted
previously.

.TP 4
.B dsctx
This points to either a buffer, filename, file pointer or file descriptor that
contains the JSON payload to be sent. See
.BR mtd_dsrc_ctx (3)
.PP
.RS 4
Scenario: Full Expenses
.PP
.RE
.RS 8
.EX
{
    "income": {
        "turnover": -599.99,
        "other": 454544.59
    },
    "expenses": {
        "costOfGoodsAllowable": 3353.39,
        "paymentsToSubcontractorsAllowable": 35353.19,
        "wagesAndStaffCostsAllowable": 24232.23,
        "carVanTravelExpensesAllowable": 3563.77,
        "premisesRunningCostsAllowable": 35635.34,
        "maintenanceCostsAllowable": 35333.22,
        "adminCostsAllowable": 24242.45,
        "interestOnBankOtherLoansAllowable": 34535.34,
        "financeChargesAllowable": 42342.56,
        "irrecoverableDebtsAllowable": 54353.23,
        "professionalFeesAllowable": 23421.23,
        "depreciationAllowable": 24222.56,
        "otherExpensesAllowable": 35435.23,
        "advertisingCostsAllowable": 34223.33,
        "businessEntertainmentCostsAllowable": 3543.78
    },
    "additions": {
        "costOfGoodsDisallowable": 5464.56,
        "paymentsToSubcontractorsDisallowable": 5643.23,
        "wagesAndStaffCostsDisallowable": 3453.78,
        "carVanTravelExpensesDisallowable": 53533.23,
        "premisesRunningCostsDisallowable": 2433.23,
        "maintenanceCostsDisallowable": 2342.53,
        "adminCostsDisallowable": 42342.34,
        "interestOnBankOtherLoansDisallowable": 2342.34,
        "financeChargesDisallowable": 23424.34,
        "irrecoverableDebtsDisallowable": 23424.23,
        "professionalFeesDisallowable": 34222.23,
        "depreciationDisallowable": 2342.54,
        "otherExpensesDisallowable": 24232.34,
        "advertisingCostsDisallowable": 23121.23,
        "businessEntertainmentCostsDisallowable": 6575.56
    }
}
.EE
.RE

.PP
.RS 4
Scenario: Consolidated Expenses
.PP
.RE
.RS 8
.EX
{
    "income": {
        "turnover": -599.99,
        "other": 454544.59
    },
    "expenses": {
        "consolidatedExpenses": 45645.23
    }
}
.EE
.RE

.TP
.B cid
.RS 4
This is the calculationId and is in the form
.RE

.RS 8
^[0-9]{8}|[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$
.RE

.TP
.B buf
.RS 4
This is the result buffer containing the JSON result string. It should be
\fBfree(3)\fP'd when no longer needed.
.RE

.SH RETURN VALUE

On success, zero (\fBMTD_ERR_NONE\fP) is returned. On error, a negative error
code is returned.

.SH ERRORS

.TP
.B -MTD_ERR_OS
There was an OS level failure

.TP 4
.B -MTD_ERR_REQUEST
The API request returned a status code >= 300

.TP
.B -MTD_ERR_CURL
There was a problem with the curl request itself

.SH SEE ALSO

.BR libmtdac (3),
.BR libmtdac_mtd.h (3),
.BR mtd_dsrc_ctx (3),
.BR libmtdac-result_buffer (3)
