.TH MTD_VAT_SUBMIT_PERIOD 3 "September 24, 2020" "" "libmtdac"

.SH NAME

mtd_vat_submit_period \- submit VAT return for period

.SH SYNOPSIS

.B #include <libmtdac/mtd-vat.h>
.PP
.nf
.BI "int mtd_vat_submit_period(const struct mtd_dsrc_ctx *" dsctx ",
.BI "                          const char *" vrn ", char **" buf );
.ni

.SH DESCRIPTION

This function allows a developer to submit a VAT return for a period

.TP 4
.B dsctx
This points to either a buffer, filename, file pointer or file descriptor that
contains the JSON payload to be sent. See
.BR mtd_dsrc_ctx (3).
The JSON should look like
.PP
.RS 8
.EX
{
    "periodKey": "A001",
    "vatDueSales": 105.50,
    "vatDueAcquisitions": -100.45,
    "totalVatDue": 5.05,
    "vatReclaimedCurrPeriod": 105.15,
    "netVatDue": 100.10,
    "totalValueSalesExVAT": 300,
    "totalValuePurchasesExVAT": 300,
    "totalValueGoodsSuppliedExVAT": 3000,
    "totalAcquisitionsExVAT": 3000,
    "finalised": true
}
.EE
.RE

.TP 3
.B vrn
This is the 9-digit VAT registration number and is in the form
.PP
.RS 8
^[0-9]{9}$
.RE

.TP
.B buf
.RS 4
This is the result buffer containing the JSON result string. It should be
\fBfree(3)\fP'd when no longer needed.
.RE

.SH RETURN VALUE

On success, zero (\fBMTD_ERR_NONE\fP) is returned. On error, a positive error
code is returned.

.SH ERRORS

.TP 4
.B MTD_ERR_REQUEST
The API request returned a status code >= 300

.TP
.B MTD_ERR_CURL
There was a problem with the curl request itself

.TP
.B MTD_ERR_OS
There was an OS level failure

.SH SEE ALSO

.BR libmtdac (3),
.BR libmtdac_mtd.h (3),
.BR mtd_dsrc_ctx (3),
.BR libmtdac-result_buffer (3)
