.TH MTD_SET_SRC_DATA 3 "June 16, 2020" "" "libmtdac"

.SH NAME

mtd_set_src_data \- set the json post data buffer

.SH SYNOPSIS

.B #include <libmtdac/mtd.h>
.PP
.BI "mtd_set_src_data(const void *" buf ", size_t " len );

.SH DESCRIPTION

Normally when POSTing data you pass in the path to the file that contains the
data to send.
.PP
However, there are times when it might be more convenient to be able to use
a buffer that contains the data. This function allows for that use case.
.PP
You call this function before you call the API function and instead of passing
a file path to the API function, you pass in \fINULL\fP.
.PP
This function takes two arguments

.TP 4
.B buf
.RS 4
This is the buffer containing the JSON data to send. The buffer contents are
\fInot\fP copied.
.RE

.TP 4
.B len
.RS 4
This is the length in bytes of the buffer.
.RE

You can use
.BR mtd_unset_src_data (3)
to reset this so you can go back to using files again.

.SH ERRORS

None. This function always succeeds.

.SH EXAMPLE

The following examples show the uses of
.BR mtd_set_src_data (3)
and
.BR mtd_unset_src_data (3)

.EX
#include <stdio.h>
#include <string.h>

#include <libmtdac/mtd-sa.h>

int main(void)
{
        const char *data = "{\\"calculationId\\": \\"041f7e4d-87d9-4d4a-a296-3cfbdf92f7e2\\"}";
        char *buf;

        mtd_init(MTD_OPT_GLOBAL_INIT);
        mtd_set_src_data(data, strlen(data));
        mtd_sa_cr_crystallise(NULL, "2018-19", &buf);
        mtd_deinit();
        printf("%s\\n", buf);

        return 0;
}
.EE

Same again but then sending a file.

.EX
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <libmtdac/mtd-sa.h>

int main(void)
{
        const char *data = "{\\"calculationId\\": \\"041f7e4d-87d9-4d4a-a296-3cfbdf92f7e2\\"}";
        char *buf;

        mtd_init(MTD_OPT_GLOBAL_INIT);
        mtd_set_src_data(data, strlen(data));
        mtd_sa_cr_crystallise(NULL, "2018-19", &buf);
        printf("%s\\n", buf);
        mtd_unset_src_data()
        free(buf);;
        mtd_sa_tc_calculate("/path/to/file", &buf);
        mtd_deinit();
        printf("%s\\n", buf);

        exit)EXIT_SUCCESS);
}
.EE

.SH SEE ALSO

.BR libmtdac (3),
.BR libmtdac_mtd.h (3),
.BR mtd_unset_src_data (3)
