.TH MTD_INIT_NINO 3 "June 1, 2020" "" "libmtdac"

.SH NAME

mtd_init_nino \- initialise national insurance number

.SH SYNOPSIS

.B #include <libmtdac/mtd.h>
.PP
.BI "int mtd_init_nino(void);"

.SH DESCRIPTION

This function is used to create an initial \fI~/.config/libmtdac/{prod,test}-api/nino.json\fP
file that contains the users \fININO\fP (National Insurance Number).
.PP
This will prompt the user to enter their NINO after which the file will be
created.
.PP
This should just be called once during an initial setup routine.

.SH RETURN VALUE

On success, zero (\fBMTD_ERR_NONE\fP) is returned. On error, a positive error
code is returned.

.SH ERRORS

.TP 4
.B MTD_ERR_OS
There was an OS level failure

.SH FILES
.I ~/.config/libmtdac/{prod,test}-api/nino.json

.SH SEE ALSO

.BR libmtdac (3),
.BR libmtdac_mtd.h (3)
