.TH MTD_IC_SA_GET_ALLOWANCES_DEDUCTIONS_RELIEFS 3 "June 7, 2020" "" "libmtdac"

.SH NAME

mtd_ic_sa_get_allowances_deductions_reliefs \- retrieve self assessment tax
calculation allowances, deductions and reliefs

.SH SYNOPSIS

.B #include <libmtdac/mtd-ic.h>
.PP
.nf
.BI "int mtd_ic_sa_get_allowances_deductions_reliefs(const char *" cid ",
.BI "                                                char **" buf );
.fi

.SH DESCRIPTION

This function allows developers to retrieve the allowances, deductions and
reliefs that have been used in the self assessment tax calculation for a given
NINO and Calculation ID (see \fBcid\fP below).

.TP 4
.B cid
.RS 4
This is the calculationId and is in the form
.RE

.RS 8
^[0-9]{8}|[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$
.RE

.TP
.B buf
.RS 4
This is the result buffer containing the JSON result string. It should be
\fBfree(3)\fP'd when no longer needed.
.RE

.SH RETURN VALUE

On success, zero (\fBMTD_ERR_NONE\fP) is returned. On error, a negative error
code is returned.

.SH ERRORS

.TP
.B -MTD_ERR_OS
There was an OS level failure

.TP 4
.B -MTD_ERR_REQUEST
The API request returned a status code >= 300

.TP
.B -MTD_ERR_CURL
There was a problem with the curl request itself

.SH SEE ALSO

.BR libmtdac (3),
.BR libmtdac_mtd.h (3),
.BR libmtdac-result_buffer (3)
