.TH MTD_GLOBAL_INIT 3 "June 10, 2020" "" "libmtdac"

.SH NAME

mtd_global_init \- global initialisation

.SH SYNOPSIS

.B #include <libmtdac/mtd.h>
.PP
.BI "void mtd_global_init(void);"

.SH DESCRIPTION

This function should be called before \fBany\fP other threads are running. In a
non-threaded application you can skip this function and pass
\fBMTD_OPT_GLOBAL_INIT\fP to
.BR mtd_init (3)
instead.

.SH ERRORS

None. This function always succeeds.

.SH SEE ALSO

.BR libmtdac (3),
.BR libmtdac_mtd.h (3),
.BR mtd_init (3),
.BR mtd_deinit (3)
