.TH MTD_BSAS_FP_UPDATE_SUMMARY_ADJUSTMENTS 3 "August 8, 2021" "" "libmtdac"

.SH NAME

mtd_bsas_fp_update_summary_adjustments \- update a foreign property Business
Source Adjustable Summary

.SH SYNOPSIS

.B #include <libmtdac/mtd-bsas.h>
.PP
.nf
.BI "int mtd_bsas_fp_update_summary_adjustments(const struct mtd_dsrc_ctx *" dsctx ",
.BI "                                           const char *" bid ", char **" buf );
.fi

.SH DESCRIPTION

This function is part of the UK's HMRC Make Tax Digital Business Source
Adjustable Summaries API.
.PP
This function allows a developer to provide accounting adjustments against a
specified Business Source Adjustable Summary (BSAS) using its unique
identifier. The BSAS ID (\fBbid\fP) used must be for a self-employment business
that has not been previously adjusted.

.TP 4
.B dsctx
This points to either a buffer, filename, file pointer or file descriptor that
contains the JSON payload to be sent. See
.BR mtd_dsrc_ctx (3)
.PP
.RS 4
Scenario: foreignProperty consolidated request
.PP
.RE
.RS 8
.EX
{
  "foreignProperty": [
    {
      "countryCode": "FRA",
      "income": {
        "rentIncome": 123.12,
        "premiumsOfLeaseGrant": 123.12,
        "otherPropertyIncome": 123.12
      },
      "expenses": {
        "consolidatedExpenses": 123.12
      }
    }
  ]
}
.EE
.RE

.PP
.RS 4
Scenario: foreignProperty unconsolidated request
.PP
.RE
.RS 8
.EX
{
  "foreignProperty": [
    {
      "countryCode": "FRA",
      "income": {
        "rentIncome": 123.12,
        "premiumsOfLeaseGrant": 123.12,
        "otherPropertyIncome": 123.12
      },
      "expenses": {
        "premisesRunningCosts": 123.12,
        "repairsAndMaintenance": 123.12,
        "financialCosts": 123.12,
        "professionalFees": 123.12,
        "travelCosts": 123.12,
        "costOfServices": 123.12,
        "residentialFinancialCost": 123.12,
        "other": 123.12
      }
    }
  ]
}
.EE
.RE

.PP
.RS 4
Scenario: foreignFhlEea consolidated request
.PP
.RE
.RS 8
.EX
{
  "foreignFhlEea": {
    "income": {
      "rentIncome": 123.12
    },
    "expenses": {
      "consolidatedExpenses": 123.12
    }
  }
}
.EE
.RE

.PP
.RS 4
Scenario: foreignFhlEea unconsolidated request
.PP
.RE
.RS 8
.EX
{
  "foreignFhlEea": {
    "income": {
      "rentIncome": 123.12
    },
    "expenses": {
      "premisesRunningCosts": 123.12,
      "repairsAndMaintenance": 123.12,
      "financialCosts": 123.12,
      "professionalFees": 123.12,
      "costOfServices": 123.12,
      "travelCosts": 123.12,
      "other": 123.12
    }
  }
}
.EE
.RE

.TP
.B bid
.RS 4
This is the bsasId and is in the form
.RE

.RS 8
^[0-9]{8}|[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$
.RE

.TP
.B buf
.RS 4
This is the result buffer containing the JSON result string. It should be
\fBfree(3)\fP'd when no longer needed.
.RE

.SH RETURN VALUE

On success, zero (\fBMTD_ERR_NONE\fP) is returned. On error, a negative error
code is returned.

.SH ERRORS

.TP
.B -MTD_ERR_OS
There was an OS level failure

.TP 4
.B -MTD_ERR_REQUEST
The API request returned a status code >= 300

.TP
.B -MTD_ERR_CURL
There was a problem with the curl request itself

.SH SEE ALSO

.BR libmtdac (3),
.BR libmtdac_mtd.h (3),
.BR mtd_dsrc_ctx (3),
.BR libmtdac-result_buffer (3)
