.TH MTD_BSAS_PB_UPDATE_SUMMARY_ADJUSTMENTS 3 "March 20, 2022" "" "libmtdac"

.SH NAME

mtd_bsas_pb_update_summary_adjustments \- update a UK property business
Business Source Adjustable Summary

.SH SYNOPSIS

.B #include <libmtdac/mtd-bsas.h>
.PP
.nf
.BI "int mtd_bsas_pb_update_summary_adjustments(const struct mtd_dsrc_ctx *" dsctx ",
.BI "                                           const char *" cid ", char **" buf );
.fi

.SH DESCRIPTION

This function is part of the UK's HMRC Make Tax Digital Business Source
Adjustable Summaries API.
.PP
This function allows a developer to provide accounting adjustments against a
specified Business Source Accounting Summary quoting its unique identifier.
The \fBcalculationID\fP quoted must be for a UK Property Business, and it must
not have been adjusted previously. Only data for one property business (either
FHL or Non-FHL) should be included in any submission.

.TP 4
.B dsctx
This points to either a buffer, filename, file pointer or file descriptor that
contains the JSON payload to be sent. See
.BR mtd_dsrc_ctx (3)
.PP
.RS 4
Scenario: Non-FHL Property with Full Expenses
.PP
.RE
.RS 8
.EX
{
    "nonFurnishedHolidayLet": {
        "income": {
            "totalRentsReceived": 1000.45,
            "premiumsOfLeaseGrant": 1000.45,
            "reversePremiums": 1000.45,
            "otherPropertyIncome": 1000.45
        },
        "expenses": {
            "premisesRunningCosts": 1000.45,
            "repairsAndMaintenance": 1000.45,
            "financialCosts": 1000.45,
            "professionalFees": 1000.45,
            "costOfServices": 1000.45,
            "residentialFinancialCost": 1000.45,
            "other": 1000.45,
            "travelCosts": 1000.45
        }
    }
}
.EE
.RE

.PP
.RS 4
Scenario: Non-FHL Property with Consolidated Expenses
.PP
.RE
.RS 8
.EX
{
    "nonFurnishedHolidayLet": {
        "income": {
            "totalRentsReceived": 1000.45,
            "premiumsOfLeaseGrant": 1000.45,
            "reversePremiums": 1000.45,
            "otherPropertyIncome": 1000.45
        },
        "expenses": {
            "consolidatedExpenses": 1000.45
        }
    }
}
.EE
.RE

.PP
.RS 4
Scenario: FHL Property with Full Expenses
.PP
.RE
.RS 8
.EX
{
    "furnishedHolidayLet": {
        "income": {
            "totalRentsReceived": 1000.45
        },
        "expenses": {
            "premisesRunningCosts": 1000.45,
            "repairsAndMaintenance": 1000.45,
            "financialCosts": 1000.45,
            "professionalFees": 1000.45,
            "costOfServices": 1000.45,
            "other": 1000.45,
            "travelCosts": 1000.45
        }
    }
}
.EE
.RE

.PP
.RS 4
Scenario: FHL Property with Consolidated Expenses
.PP
.RE
.RS 8
.EX
{
    "furnishedHolidayLet": {
        "income": {
            "totalRentsReceived": 1000.45
        },
        "expenses": {
            "consolidatedExpenses": 1000.45
        }
    }
}
.EE
.RE

.TP
.B cid
.RS 4
This is the calculationId and is in the form
.RE

.RS 8
^[0-9]{8}|[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$
.RE

.TP
.B buf
.RS 4
This is the result buffer containing the JSON result string. It should be
\fBfree(3)\fP'd when no longer needed.
.RE

.SH RETURN VALUE

On success, zero (\fBMTD_ERR_NONE\fP) is returned. On error, a negative error
code is returned.

.SH ERRORS

.TP
.B -MTD_ERR_OS
There was an OS level failure

.TP 4
.B -MTD_ERR_REQUEST
The API request returned a status code >= 300

.TP
.B -MTD_ERR_CURL
There was a problem with the curl request itself

.SH SEE ALSO

.BR libmtdac (3),
.BR libmtdac_mtd.h (3),
.BR mtd_dsrc_ctx (3),
.BR libmtdac-result_buffer (3)
