.TH MTD_ISI_SI_O_GET 3 "April 19, 2025" "" "libmtdac"

.SH NAME

mtd_isi_si_o_get \- retrieve savings income for securities and foreign interest

.SH SYNOPSIS

.B #include <libmtdac/mtd-isi.h>
.PP
.BI "int mtd_isi_si_o_get(const char *" tax_year ", char **" buf );

.SH DESCRIPTION

This function allows a developer to retrieve savings income for securities
and foreign interest.

.TP 4
.B tax_year
This is taxYear and is in the form
.PP
.RS 8
YYYY-YY
.RE

.TP
.B buf
.RS 4
This is the result buffer containing the JSON result string. It should be
\fBfree(3)\fP'd when no longer needed.
.RE

.SH RETURN VALUE

On success, zero (\fBMTD_ERR_NONE\fP) is returned. On error, a negative error
code is returned.

.SH ERRORS

.TP
.B -MTD_ERR_OS
There was an OS level failure

.TP 4
.B -MTD_ERR_REQUEST
The API request returned a status code >= 300

.TP
.B -MTD_ERR_CURL
There was a problem with the curl request itself

.SH SEE ALSO

.BR libmtdac (3),
.BR libmtdac_mtd.h (3),
.BR libmtdac-result_buffer (3)
