.TH MTD_ERR2ENUM_STR 3 "January 23, 2021" "" "libmtdac"

.SH NAME

mtd_err2enum_str \- error code to description

.SH SYNOPSIS

.B #include <libmtdac/mtd.h>
.PP
.BI "const char *mtd_err2enum_str(int " err );

.SH DESCRIPTION

This function returns a string version of the given error code enum.

.TP 3
.B err
An integer error code such as returned by the mtd_* functions.

.SH RETURN VALUE

A const character pointer to a stringified version of the error code..

.SH SEE ALSO

.BR libmtdac (3),
.BR libmtdac_mtd.h (3)
