.TH MTD_HDRS_ADD 3 "June 11, 2020" "" "libmtdac"

.SH NAME

mtd_hdrs_add \- add extra HTTP headers to send

.SH SYNOPSIS

.B #include <libmtdac/mtd.h>
.PP
.BI "void mtd_hdrs_add(const char * const " hdrs []);

.SH DESCRIPTION

This function can be used to add extra HTTP headers to send. These headers will
persist across API calls as long as you leave \fBhdrs\fP intact.
.PP
You can either change them with another call to
.BR mtd_hdrs_add (3)
or clear them with
.BR mtd_hdrs_reset (3)

.TP 4
.B hdrs
.RS 4
This is a \fBNULL\fP terminated array of pointers to NUL terminated strings. E.g
.RE

.RS 8
.EX
const char *hdrs[2] = { NULL };

hdrs[0] = "My-Header: some value";
mtd_hdrs_add(hdrs);
.EE
.RE

.SH ERRORS

None. This function always succeeds.

.SH SEE ALSO

.BR libmtdac (3),
.BR libmtdac_mtd.h (3),
.BR mtd_hdrs_reset (3)
