.TH MTD_IC_FINAL_DECL 3 "July 29, 2022" "" "libmtdac"

.SH NAME

mtd_ic_final_decl \- submit a final declaration

.SH SYNOPSIS

.B #include <libmtdac/mtd-ic.h>
.PP
.nf
.BI "int mtd_ic_final_decl(const char *" tax_year ", const char *" cid ",
.BI "                      char **" buf );
.fi

.SH DESCRIPTION

This function allows developers to submit a final declaration for a tax year
(\fBtax_year\fP) and calulation ID (\fBcid\fP), by agreeing to the HMRC's tax
calculation.

.TP 4
.B tax_year
This is the Tax year to operate on and is in the form
.RE

.RS 8
YYYY-YY
.RE

.TP
.B cid
.RS 4
This is the calculationId and is in the form
.RE

.RS 8
^[0-9]{8}|[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$
.RE

.TP
.B buf
.RS 4
This is the result buffer containing the JSON result string. It should be
\fBfree(3)\fP'd when no longer needed.
.RE

.SH RETURN VALUE

On success, zero (\fBMTD_ERR_NONE\fP) is returned. On error, a negative error
code is returned.

.SH ERRORS

.TP
.B -MTD_ERR_OS
There was an OS level failure

.TP 4
.B -MTD_ERR_REQUEST
The API request returned a status code >= 300

.TP
.B -MTD_ERR_CURL
There was a problem with the curl request itself

.SH SEE ALSO

.BR libmtdac (3),
.BR libmtdac_mtd.h (3),
.BR mtd_dsrc_ctx (3),
.BR libmtdac-result_buffer (3)

.PP
HMRC documentation for this endpoint can be found at
.PP

.in +4
.nf
.B https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/individual-calculations-api/3.0#Submit a Self Assessment Final Declaration
.fi
