.TH MTD_ISI_SI_UA_GET_ANNUAL_SUMMARY 3 "April 19, 2025" "" "libmtdac"

.SH NAME

mtd_isi_si_ua_get_annual_summary \- retrieve a UK savings account annual
summary for a tax year

.SH SYNOPSIS

.B #include <libmtdac/mtd-isi.h>
.PP
.nf
.BI "int mtd_isi_si_ua_get_annual_summary(const char *" yax_year ",
.BI "                                     const char *" said ",
.BI "                                     char **" buf );
.fi

.SH DESCRIPTION

This function allows a developer to retrieve a UK savings account annual
summary for a tax year. (see \fBtax_year\fP & \fBsaid\fP below).

.TP
.B tax_year
This is the taxYear and is in the form
.PP
.RS 9
YYYY-YY
.RE

.TP 4
.B said
This is the savingsAccountId and is in the form
.PP
.RS 8
^[A-Za-z0-9]{15}$
.RE

.TP
.B buf
.RS 4
This is the result buffer containing the JSON result string. It should be
\fBfree(3)\fP'd when no longer needed.
.RE

.SH RETURN VALUE

On success, zero (\fBMTD_ERR_NONE\fP) is returned. On error, a negative error
code is returned.

.SH ERRORS

.TP
.B -MTD_ERR_OS
There was an OS level failure

.TP 4
.B -MTD_ERR_REQUEST
The API request returned a status code >= 300

.TP
.B -MTD_ERR_CURL
There was a problem with the curl request itself

.SH SEE ALSO

.BR libmtdac (3),
.BR libmtdac_mtd.h (3),
.BR libmtdac-result_buffer (3)
