.TH MTD_BISS_GET_SELF_EMPLOYMENT 3 "June 1, 2020" "" "libmtdac"

.SH NAME

mtd_biss_get_self_employment \- get a self-employment summary from BISS

.SH SYNOPSIS

.B #include <libmtdac/mtd-biss.h>

.BI "int mtd_biss_get_self_employment(const char *" query_string ", char **" buf ");"

.SH DESCRIPTION

This function is part of the UK's HMRC Make Tax Digital Business Income Source
Summary API.
.PP
This function allows a developer to retrieve a running year-to-date (YTD)
summary of the income and expenditure for a specified self-employment business
during a tax year.

.TP 4
.B query_string
This is required and is of the form
.PP
.RS 8
\fB?selfEmploymentId=XNISNNNNNNNNNNN\fP[&taxYear=YYYY-YY]
.RE

.RS 4
\fBselfEmploymentId\fP is required and is in the form
.RE

.RS 8
^X[A-Z0-9]{1}IS[0-9]{11}$
.RE

.RS 4
\fBtaxYear\fP is an optional tax year.
.RE

.TP
.B buf
.RS 4
This is the result buffer containing the JSON result string. It should be
\fBfree(3)\fP'd when no longer needed.
.RE

.SH RETURN VALUE

On success, zero (\fBMTD_ERR_NONE\fP) is returned. On error, a negative error
code is returned.

.SH ERRORS

.TP 4

.TP
.B -MTD_ERR_OS
There was an OS level failure

.B -MTD_ERR_REQUEST
The API request returned a status code >= 300

.TP
.B -MTD_ERR_CURL
There was a problem with the curl request itself

.SH SEE ALSO

.BR libmtdac (3),
.BR libmtdac_mtd.h (3),
.BR libmtdac-result_buffer (3)
