.TH MTD_INIT_CREDS 3 "September 22, 2021" "" "libmtdac"

.SH NAME

mtd_init_creds \- initialise creds.json

.SH SYNOPSIS

.B #include <libmtdac/mtd.h>
.PP
.BI "int mtd_init_creds(enum mtd_ep_api " api );

.SH DESCRIPTION

This function is used to create an initial
\fI${CONFIG_DIR}/libmtdac/{prod,test}-api/creds.json\fP file that contains
the users \fIclient_id\fP & \fIclient_secret\fP.
.PP
This will prompt the user to enter the above tokens after which the file will
be created.
.PP
This should just be called once during an initial setup routine.

.I api
is an enum value specifying which Make Tax Digital API this is adding
credentials for and is one of the following values
.PP
.B MTD_EP_API_ITSA
.RS 4
For Income TAX Self-Assessment
.RE
.PP
.B MTD_EP_API_VAT
.RS 4
For VAT
.RE

.PP
The above can optionally be bitwise OR'd with
.PP
\fBMTD_EP_API_ADD\fP
.PP
which says don't reset the creds.json file when writing it, instead add these
credentials as another entry (or overwrite an existing entry without resetting
the file).

.SH RETURN VALUE

On success, zero (\fBMTD_ERR_NONE\fP) is returned. On error, a negative error
code is returned.

.SH ERRORS

.TP 4
.B -MTD_ERR_OS
There was an OS level failure

.TP 4
.B -MTD_ERR_INVALID_EP_API
An invalid endpoint API was specified

.SH FILES
.I ${CONFIG_DIR}/libmtdac/{prod,test}-api/creds.json

.SH SEE ALSO

.BR libmtdac (3),
.BR libmtdac_mtd.h (3)
