.TH MTD_IL_BF_LIST_LOSES 3 "August 23, 2021" "" "libmtdac"

.SH NAME

mtd_il_bf_list_loses \- list individual brought forward loses

.SH SYNOPSIS

.B #include <libmtdac/mtd-il.h>
.PP
.BI "int mtd_il_bf_list_loses(const char *" query_string ", char **" buf );

.SH DESCRIPTION

This function allows developers to retrieve a list of all brought forward
losses which have incurred before joining MTD.

.TP 4
.B query_string
This is optional and is of the form
.PP
.RS 8
[?[businessId=XNISNNNNNNNNNNN][&[taxYear=YYYY-YY][&[typeOfLoss={self-employment,uk-property-fhl,uk-property-non-fhl}]]]]
.RE

.RS 4
\fBbusinessId\fP is optional and is in the form
.RE

.RS 8
^X[A-Z0-9]{1}IS[0-9]{11}$
.RE

.RS 4
\fBtaxYear\fP is an optional tax year.

\fBtypeOfLoss\fP is optional and is \fBone\fP of the above shown values.
.RE

.TP
.B buf
.RS 4
This is the result buffer containing the JSON result string. It should be
\fBfree(3)\fP'd when no longer needed.
.RE

.SH RETURN VALUE

On success, zero (\fBMTD_ERR_NONE\fP) is returned. On error, a negative error
code is returned.

.SH ERRORS

.TP
.B -MTD_ERR_OS
There was an OS level failure

.TP 4
.B -MTD_ERR_REQUEST
The API request returned a status code >= 300

.TP
.B -MTD_ERR_CURL
There was a problem with the curl request itself

.SH SEE ALSO

.BR libmtdac (3),
.BR libmtdac_mtd.h (3),
.BR libmtdac-result_buffer (3)
