.TH MTD_TEST_CU_CREATE_INDIVIDUAL 3 "June 7, 2020" "" "libmtdac"

.SH NAME

mtd_test_cu_create_individual \- create a test user which is an individual

.SH SYNOPSIS

.B #include <libmtdac/mtd-test-cu.h>
.PP
.BI "int mtd_test_cu_create_individual(const char *" src_file ", char **" buf );

.SH DESCRIPTION

This function creates and returns a test user which is an \fBindividual\fP. The
caller can specify the required service enrolments in the request body. If no
request body is supplied, the test user is created with no service enrolments.

.TP 4
.B src_file
This is a file containing the JSON payload to send. E.g
.PP
.RS 8
.EX
{
    "serviceNames": [
        "national-insurance",
        "self-assessment",
        "mtd-income-tax",
        "customs-services",
        "mtd-vat",
        "ics-safety-and-security"
    ]
}
.EE
.RE

.TP
.B buf
.RS 4
This is the result buffer containing the JSON result string. It should be
\fBfree(3)\fP'd when no longer needed.
.RE

.SH RETURN VALUE

On success, zero (\fBMTD_ERR_NONE\fP) is returned. On error, a positive error
code is returned.

.SH ERRORS

.TP 4
.B MTD_ERR_REQUEST
The API request returned a status code >= 300

.TP
.B MTD_ERR_CURL
There was a problem with the curl request itself

.TP
.B MTD_ERR_OS
There was an OS level failure

.SH SEE ALSO

.BR libmtdac (3),
.BR libmtdac_mtd.h (3),
.BR libmtdac-result_buffer (3)
