.TH MTD_IL_BF_CREATE_LOSS 3 "April 3, 2022" "" "libmtdac"

.SH NAME

mtd_il_bf_create_loss \- create individual brought forward loss

.SH SYNOPSIS

.B #include <libmtdac/mtd-il.h>
.PP
.nf
.BI "int mtd_il_bf_create_loss(const struct mtd_dsrc_ctx *" dsctx ", char **" buf );
.fi

.SH DESCRIPTION

This function allows developers to create a new brought forward loss which can
be submitted against self-employment, self-employment class 4, UK Furnished
Holiday Let (FHL) property, UK other (Non-FHL) property, foreign property FHL
in the European Economic Area (EEA) and foreign property for the tax year
prior to joining MTD.

.TP 4
.B dsctx
This points to either a buffer, filename, file pointer or file descriptor that
contains the JSON payload to be sent. See
.BR mtd_dsrc_ctx (3)
.PP
.RS 4
Scenario: Self-Employment Request
.PP
.RE
.RS 8
.EX
{
    "taxYearBroughtForwardFrom": "2020-21",
    "businessId": "XBIS12345678910",
    "typeOfLoss": "self-employment",
    "lossAmount": 5001.99
}
.EE
.RE
.PP
.RE
.RS 4
Scenario: UK FHL Property Request
.PP
.RE
.RS 8
.EX
{
    "taxYearBroughtForwardFrom": "2020-21",
    "businessId": "XPIS12345678910",
    "typeOfLoss": "uk-property-fhl",
    "lossAmount": 500.99
}
.EE
.RE
.PP
.RS 4
Scenario: Foreign Property Request
.PP
.RE
.RS 8
.EX
{
    "taxYearBroughtForwardFrom": "2020-21",
    "businessId": "XFIS12345678910",
    "typeOfLoss": "foreign-property",
    "lossAmount": 5000.99
}
.EE
.RE

.PP

.TP
.B buf
.RS 4
This is the result buffer containing the JSON result string. It should be
\fBfree(3)\fP'd when no longer needed.
.RE

.SH RETURN VALUE

On success, zero (\fBMTD_ERR_NONE\fP) is returned. On error, a negative error
code is returned.

.SH ERRORS

.TP
.B -MTD_ERR_OS
There was an OS level failure

.TP 4
.B -MTD_ERR_REQUEST
The API request returned a status code >= 300

.TP
.B -MTD_ERR_CURL
There was a problem with the curl request itself

.SH SEE ALSO

.BR libmtdac (3),
.BR libmtdac_mtd.h (3),
.BR mtd_dsrc_ctx (3),
.BR libmtdac-result_buffer (3)
