.TH MTD_INIT_CREDS 3 "September 21, 2021" "" "libmtdac"

.SH NAME

mtd_init_creds \- initialise creds.json

.SH SYNOPSIS

.B #include <libmtdac/mtd.h>
.PP
.BI "int mtd_init_creds(void);"

.SH DESCRIPTION

This function is used to create an initial
\fI${CONFIG_DIR}/libmtdac/{prod,test}-api/creds.json\fP file that contains
the users \fIclient_id\fP & \fIclient_secret\fP.
.PP
This will prompt the user to enter the above tokens after which the file will
be created.
.PP
This should just be called once during an initial setup routine.

.SH RETURN VALUE

On success, zero (\fBMTD_ERR_NONE\fP) is returned. On error, a negative error
code is returned.

.SH ERRORS

.TP 4
.B -MTD_ERR_OS
There was an OS level failure

.SH FILES
.I ${CONFIG_DIR}/libmtdac/{prod,test}-api/creds.json

.SH SEE ALSO

.BR libmtdac (3),
.BR libmtdac_mtd.h (3)
