/* SPDX-License-Identifier: LGPL-2.1 */

/*
 * mtd-hmrc-err.c - Make Tax Digital API Errors
 *
 * Copyright (C) 2020 - 2022	Andrew Clayton <andrew@digital-domain.net>
 */

#define _GNU_SOURCE

#include <string.h>

#include <jansson.h>

#include "mtd.h"

static const struct _mtd_hmrc_err_map {
	const char *str;
} mtd_hmrc_err_map[] = {
	[MTD_HMRC_ERR_MULTIPLE] = {
		.str = "MTD_HMRC_ERR_MULTIPLE"
	},

	[MTD_HMRC_ERR_CLIENT_OR_AGENT_NOT_AUTHORISED] = {
		.str = "CLIENT_OR_AGENT_NOT_AUTHORISED"
	},
	[MTD_HMRC_ERR_END_OF_YEAR_ESTIMATE_NOT_PRESENT] = {
		.str = "END_OF_YEAR_ESTIMATE_NOT_PRESENT"
	},
	[MTD_HMRC_ERR_FORMAT_ADJUSTED_STATUS] = {
		.str = "FORMAT_ADJUSTED_STATUS"
	},
	[MTD_HMRC_ERR_FORMAT_ADJUSTMENT_VALUE] = {
		.str = "FORMAT_ADJUSTMENT_VALUE"
	},
	[MTD_HMRC_ERR_FORMAT_ASSET_DESCRIPTION] = {
		.str = "FORMAT_ASSET_DESCRIPTION"
	},
	[MTD_HMRC_ERR_FORMAT_ASSET_TYPE] = {
		.str = "FORMAT_ASSET_TYPE"
	},
	[MTD_HMRC_ERR_FORMAT_BENEFIT_ID] = {
		.str = "FORMAT_BENEFIT_ID"
	},
	[MTD_HMRC_ERR_FORMAT_BENEFIT_TYPE] = {
		.str = "FORMAT_BENEFIT_TYPE"
	},
	[MTD_HMRC_ERR_FORMAT_BSAS_ID] = {
		.str = "FORMAT_BSAS_ID"
	},
	[MTD_HMRC_ERR_FORMAT_BUSINESS_ID] = {
		.str = "FORMAT_BUSINESS_ID"
	},
	[MTD_HMRC_ERR_FORMAT_CALC_ID] = {
		.str = "FORMAT_CALC_ID"
	},
	[MTD_HMRC_ERR_FORMAT_CESSATION_DATE] = {
		.str = "FORMAT_CESSATION_DATE"
	},
	[MTD_HMRC_ERR_FORMAT_CLAIM_ID] = {
		.str = "FORMAT_CLAIM_ID"
	},
	[MTD_HMRC_ERR_FORMAT_CLAIM_OR_ELECTION_CODES] = {
		.str = "FORMAT_CLAIM_OR_ELECTION_CODES"
	},
	[MTD_HMRC_ERR_FORMAT_CLAIM_TYPE] = {
		.str = "FORMAT_CLAIM_TYPE"
	},
	[MTD_HMRC_ERR_FORMAT_CLASS_OF_SHARES_ACQUIRED] = {
		.str = "FORMAT_CLASS_OF_SHARES_ACQUIRED"
	},
	[MTD_HMRC_ERR_FORMAT_CLASS_OF_SHARES_AWARDED] = {
		.str = "FORMAT_CLASS_OF_SHARES_AWARDED"
	},
	[MTD_HMRC_ERR_FORMAT_COUNTRY_CODE] = {
		.str = "FORMAT_COUNTRY_CODE"
	},
	[MTD_HMRC_ERR_FORMAT_CUSTOMER_REF] = {
		.str = "FORMAT_CUSTOMER_REF"
	},
	[MTD_HMRC_ERR_FORMAT_CUSTOMER_REFERENCE] = {
		.str = "FORMAT_CUSTOMER_REFERENCE"
	},
	[MTD_HMRC_ERR_FORMAT_DATE] = {
		.str = "FORMAT_DATE"
	},
	[MTD_HMRC_ERR_FORMAT_DATE_OF_INVESTMENT] = {
		.str = "FORMAT_DATE_OF_INVESTMENT"
	},
	[MTD_HMRC_ERR_FORMAT_DEDUCTIONS_FROM_DATE] = {
		.str = "FORMAT_DEDUCTIONS_FROM_DATE"
	},
	[MTD_HMRC_ERR_FORMAT_DEDUCTIONS_TO_DATE] = {
		.str = "FORMAT_DEDUCTIONS_TO_DATE"
	},
	[MTD_HMRC_ERR_FORMAT_DOUBLE_TAXATION_ARTICLE] = {
		.str = "FORMAT_DOUBLE_TAXATION_ARTICLE"
	},
	[MTD_HMRC_ERR_FORMAT_DOUBLE_TAXATION_TREATY] = {
		.str = "FORMAT_DOUBLE_TAXATION_TREATY"
	},
	[MTD_HMRC_ERR_FORMAT_EMPLOYER_NAME] = {
		.str = "FORMAT_EMPLOYER_NAME"
	},
	[MTD_HMRC_ERR_FORMAT_EMPLOYER_REF] = {
		.str = "FORMAT_EMPLOYER_REF"
	},
	[MTD_HMRC_ERR_FORMAT_EMPLOYER_REFERENCE] = {
		.str = "FORMAT_EMPLOYER_REFERENCE"
	},
	[MTD_HMRC_ERR_FORMAT_EMPLOYMENT_ID] = {
		.str = "FORMAT_EMPLOYMENT_ID"
	},
	[MTD_HMRC_ERR_FORMAT_END_DATE] = {
		.str = "FORMAT_END_DATE"
	},
	[MTD_HMRC_ERR_FORMAT_EVENT] = {
		.str = "FORMAT_EVENT"
	},
	[MTD_HMRC_ERR_FORMAT_FINALISED] = {
		.str = "FORMAT_FINALISED"
	},
	[MTD_HMRC_ERR_FORMAT_FROM_DATE] = {
		.str = "FORMAT_FROM_DATE"
	},
	[MTD_HMRC_ERR_FORMAT_ID] = {
		.str = "FORMAT_ID"
	},
	[MTD_HMRC_ERR_FORMAT_INCOME_SOURCE] = {
		.str = "FORMAT_INCOME_SOURCE"
	},
	[MTD_HMRC_ERR_FORMAT_LENDER_NAME] = {
		.str = "FORMAT_LENDER_NAME"
	},
	[MTD_HMRC_ERR_FORMAT_LOSS_AMOUNT] = {
		.str = "FORMAT_LOSS_AMOUNT"
	},
	[MTD_HMRC_ERR_FORMAT_LOSS_ID] = {
		.str = "FORMAT_LOSS_ID"
	},
	[MTD_HMRC_ERR_FORMAT_NAME] = {
		.str = "FORMAT_NAME"
	},
	[MTD_HMRC_ERR_FORMAT_NAME_BUSINESS] = {
		.str = "FORMAT_NAME_BUSINESS"
	},
	[MTD_HMRC_ERR_FORMAT_NAME_EX_SPOUSE] = {
		.str = "FORMAT_NAME_EX_SPOUSE"
	},
	[MTD_HMRC_ERR_FORMAT_NAME_OF_SHIP] = {
		.str = "FORMAT_NAME_OF_SHIP"
	},
	[MTD_HMRC_ERR_FORMAT_NATURE_OF_TRADE] = {
		.str = "FORMAT_NATURE_OF_TRADE"
	},
	[MTD_HMRC_ERR_FORMAT_NINO] = {
		.str = "FORMAT_NINO"
	},
	[MTD_HMRC_ERR_FORMAT_PAYMENT_ID] = {
		.str = "FORMAT_PAYMENT_ID"
	},
	[MTD_HMRC_ERR_FORMAT_PAYROLL_ID] = {
		.str = "FORMAT_PAYROLL_ID"
	},
	[MTD_HMRC_ERR_FORMAT_PENSION_SCHEME_TAX_REFERENCE] = {
		.str = "FORMAT_PENSION_SCHEME_TAX_REFERENCE"
	},
	[MTD_HMRC_ERR_FORMAT_PPD_SUBMISSION_ID] = {
		.str = "FORMAT_PPD_SUBMISSION_ID"
	},
	[MTD_HMRC_ERR_FORMAT_PROVIDER_NAME] = {
		.str = "FORMAT_PROVIDER_NAME"
	},
	[MTD_HMRC_ERR_FORMAT_PROVIDERS_ADDRESS] = {
		.str = "FORMAT_PROVIDERS_ADDRESS"
	},
	[MTD_HMRC_ERR_FORMAT_QOPS_REF] = {
		.str = "FORMAT_QOPS_REF"
	},
	[MTD_HMRC_ERR_FORMAT_SCHEME_PLAN_TYPE] = {
		.str = "FORMAT_SCHEME_PLAN_TYPE"
	},
	[MTD_HMRC_ERR_FORMAT_SELF_EMPLOYMENT_ID] = {
		.str = "FORMAT_SELF_EMPLOYMENT_ID"
	},
	[MTD_HMRC_ERR_FORMAT_SEQUENCE] = {
		.str = "FORMAT_SEQUENCE"
	},
	[MTD_HMRC_ERR_FORMAT_SF74_REF] = {
		.str = "FORMAT_SF74_REF"
	},
	[MTD_HMRC_ERR_FORMAT_SOURCE] = {
		.str = "FORMAT_SOURCE"
	},
	[MTD_HMRC_ERR_FORMAT_SPOUSE_OR_CIVIL_PARTNERS_DATE_OF_BIRTH] = {
		.str = "FORMAT_SPOUSE_OR_CIVIL_PARTNERS_DATE_OF_BIRTH"
	},
	[MTD_HMRC_ERR_FORMAT_SPOUSE_OR_CIVIL_PARTNERS_FIRST_NAME] = {
		.str = "FORMAT_SPOUSE_OR_CIVIL_PARTNERS_FIRST_NAME"
	},
	[MTD_HMRC_ERR_FORMAT_SPOUSE_OR_CIVIL_PARTNERS_NINO] = {
		.str = "FORMAT_SPOUSE_OR_CIVIL_PARTNERS_NINO"
	},
	[MTD_HMRC_ERR_FORMAT_SPOUSE_OR_CIVIL_PARTNERS_SURNAME] = {
		.str = "FORMAT_SPOUSE_OR_CIVIL_PARTNERS_SURNAME"
	},
	[MTD_HMRC_ERR_FORMAT_SRN_INVALID] = {
		.str = "FORMAT_SRN_INVALID"
	},
	[MTD_HMRC_ERR_FORMAT_START_DATE] = {
		.str = "FORMAT_START_DATE"
	},
	[MTD_HMRC_ERR_FORMAT_STATUS] = {
		.str = "FORMAT_STATUS"
	},
	[MTD_HMRC_ERR_FORMAT_STRING] = {
		.str = "FORMAT_STRING"
	},
	[MTD_HMRC_ERR_FORMAT_SUBMISSION_ID] = {
		.str = "FORMAT_SUBMISSION_ID"
	},
	[MTD_HMRC_ERR_FORMAT_TAX_YEAR] = {
		.str = "FORMAT_TAX_YEAR"
	},
	[MTD_HMRC_ERR_FORMAT_TO_DATE] = {
		.str = "FORMAT_TO_DATE"
	},
	[MTD_HMRC_ERR_FORMAT_TRANSACTION_ID] = {
		.str = "FORMAT_TRANSACTION_ID"
	},
	[MTD_HMRC_ERR_FORMAT_TYPE] = {
		.str = "FORMAT_TYPE"
	},
	[MTD_HMRC_ERR_FORMAT_TYPE_OF_BUSINESS] = {
		.str = "FORMAT_TYPE_OF_BUSINESS"
	},
	[MTD_HMRC_ERR_FORMAT_TYPE_OF_CLAIM] = {
		.str = "FORMAT_TYPE_OF_CLAIM"
	},
	[MTD_HMRC_ERR_FORMAT_TYPE_OF_LOSS] = {
		.str = "FORMAT_TYPE_OF_LOSS"
	},
	[MTD_HMRC_ERR_FORMAT_UNIQUE_INVESTMENT_REFERENCE] = {
		.str = "FORMAT_UNIQUE_INVESTMENT_REFERENCE"
	},
	[MTD_HMRC_ERR_FORMAT_VALUE] = {
		.str = "FORMAT_VALUE"
	},
	[MTD_HMRC_ERR_MATCHING_RESOURCE_NOT_FOUND] = {
		.str = "MATCHING_RESOURCE_NOT_FOUND"
	},
	[MTD_HMRC_ERR_MISSING_FROM_DATE] = {
		.str = "MISSING_FROM_DATE"
	},
	[MTD_HMRC_ERR_MISSING_TO_DATE] = {
		.str = "MISSING_TO_DATE"
	},
	[MTD_HMRC_ERR_MISSING_TYPE_OF_BUSINESS] = {
		.str = "MISSING_TYPE_OF_BUSINESS"
	},
	[MTD_HMRC_ERR_NO_BUSINESS_FOUND] = {
		.str = "NO_BUSINESS_FOUND"
	},
	[MTD_HMRC_ERR_NO_DETAILS_FOUND] = {
		.str = "NO_DETAILS_FOUND"
	},
	[MTD_HMRC_ERR_NO_MESSAGES_PRESENT] = {
		.str = "NO_MESSAGES_PRESENT"
	},
	[MTD_HMRC_ERR_NO_OBLIGATIONS_FOUND] = {
		.str = "NO_OBLIGATIONS_FOUND"
	},
	[MTD_HMRC_ERR_PPD_SUBMISSION_ID_NOT_FOUND] = {
		.str = "PPD_SUBMISSION_ID_NOT_FOUND"
	},
	[MTD_HMRC_ERR_RANGE_DATE_TOO_LONG] = {
		.str = "RANGE_DATE_TOO_LONG"
	},
	[MTD_HMRC_ERR_RANGE_END_DATE_BEFORE_START_DATE] = {
		.str = "RANGE_END_DATE_BEFORE_START_DATE"
	},
	[MTD_HMRC_ERR_RANGE_TO_DATE_BEFORE_FROM_DATE] = {
		.str = "RANGE_TO_DATE_BEFORE_FROM_DATE"
	},
	[MTD_HMRC_ERR_RULE_ACCOUNTING_PERIOD_NOT_ENDED] = {
		.str = "RULE_ACCOUNTING_PERIOD_NOT_ENDED"
	},
	[MTD_HMRC_ERR_RULE_ACCOUNTING_PERIOD_NOT_SUPPORTED] = {
		.str = "RULE_ACCOUNTING_PERIOD_NOT_SUPPORTED"
	},
	[MTD_HMRC_ERR_RULE_ACQUISITION_DATE] = {
		.str = "RULE_ACQUISITION_DATE"
	},
	[MTD_HMRC_ERR_RULE_ACQUISITION_DATE_AFTER_DISPOSAL_DATE] = {
		.str = "RULE_ACQUISITION_DATE_AFTER_DISPOSAL_DATE"
	},
	[MTD_HMRC_ERR_RULE_ACTIVE_MARRIAGE_ALLOWANCE_CLAIM] = {
		.str = "RULE_ACTIVE_MARRIAGE_ALLOWANCE_CLAIM"
	},
	[MTD_HMRC_ERR_RULE_ALREADY_EXISTS] = {
		.str = "RULE_ALREADY_EXISTS"
	},
	[MTD_HMRC_ERR_RULE_ALREADY_SUBMITTED] = {
		.str = "RULE_ALREADY_SUBMITTED"
	},
	[MTD_HMRC_ERR_RULE_AMOUNT_GAIN_LOSS] = {
		.str = "RULE_AMOUNT_GAIN_LOSS"
	},
	[MTD_HMRC_ERR_RULE_BENEFIT_TYPE_EXISTS] = {
		.str = "RULE_BENEFIT_TYPE_EXISTS"
	},
	[MTD_HMRC_ERR_RULE_BOTH_ALLOWANCES_SUPPLIED] = {
		.str = "RULE_BOTH_ALLOWANCES_SUPPLIED"
	},
	[MTD_HMRC_ERR_RULE_BOTH_EXPENSES_SUPPLIED] = {
		.str = "RULE_BOTH_EXPENSES_SUPPLIED"
	},
	[MTD_HMRC_ERR_RULE_BSAS_ALREADY_ADJUSTED] = {
		.str = "RULE_BSAS_ALREADY_ADJUSTED"
	},
	[MTD_HMRC_ERR_RULE_BUILDING_NAME_NUMBER] = {
		.str = "RULE_BUILDING_NAME_NUMBER"
	},
	[MTD_HMRC_ERR_RULE_BUSINESS_ID] = {
		.str = "RULE_BUSINESS_ID"
	},
	[MTD_HMRC_ERR_RULE_CALCULATION_ERROR_MESSAGES_EXIST] = {
		.str = "RULE_CALCULATION_ERROR_MESSAGES_EXIST"
	},
	[MTD_HMRC_ERR_RULE_CESSATION_DATE_BEFORE_TAX_YEAR_START] = {
		.str = "RULE_CESSATION_DATE_BEFORE_TAX_YEAR_START"
	},
	[MTD_HMRC_ERR_RULE_CLASS4_OVER_16] = {
		.str = "RULE_CLASS4_OVER_16"
	},
	[MTD_HMRC_ERR_RULE_CLASS4_PENSION_AGE] = {
		.str = "RULE_CLASS4_PENSION_AGE"
	},
	[MTD_HMRC_ERR_RULE_COMPLETION_DATE] = {
		.str = "RULE_COMPLETION_DATE"
	},
	[MTD_HMRC_ERR_RULE_COMPLETION_DATE_BEFORE_DISPOSAL_DATE] = {
		.str = "RULE_COMPLETION_DATE_BEFORE_DISPOSAL_DATE"
	},
	[MTD_HMRC_ERR_RULE_CONSOLIDATED_EXPENSES] = {
		.str = "RULE_CONSOLIDATED_EXPENSES"
	},
	[MTD_HMRC_ERR_RULE_COST_OF_MATERIALS] = {
		.str = "RULE_COST_OF_MATERIALS"
	},
	[MTD_HMRC_ERR_RULE_COUNTRY_CODE] = {
		.str = "RULE_COUNTRY_CODE"
	},
	[MTD_HMRC_ERR_RULE_CUSTOM_EMPLOYMENT] = {
		.str = "RULE_CUSTOM_EMPLOYMENT"
	},
	[MTD_HMRC_ERR_RULE_DATE_RANGE_INVALID] = {
		.str = "RULE_DATE_RANGE_INVALID"
	},
	[MTD_HMRC_ERR_RULE_DATE_RANGE_OUT_OF_DATE] = {
		.str = "RULE_DATE_RANGE_OUT_OF_DATE"
	},
	[MTD_HMRC_ERR_RULE_DECEASED_RECIPIENT] = {
		.str = "RULE_DECEASED_RECIPIENT"
	},
	[MTD_HMRC_ERR_RULE_DEDUCTIONS_AMOUNT] = {
		.str = "RULE_DEDUCTIONS_AMOUNT"
	},
	[MTD_HMRC_ERR_RULE_DEDUCTIONS_DATE_RANGE_INVALID] = {
		.str = "RULE_DEDUCTIONS_DATE_RANGE_INVALID"
	},
	[MTD_HMRC_ERR_RULE_DELETE_AFTER_CRYSTALLISATION] = {
		.str = "RULE_DELETE_AFTER_CRYSTALLISATION"
	},
	[MTD_HMRC_ERR_RULE_DELETE_FORBIDDEN] = {
		.str = "RULE_DELETE_FORBIDDEN"
	},
	[MTD_HMRC_ERR_RULE_DISPOSAL_DATE] = {
		.str = "RULE_DISPOSAL_DATE"
	},
	[MTD_HMRC_ERR_RULE_DUPLICATE_COUNTRY_CODE] = {
		.str = "RULE_DUPLICATE_COUNTRY_CODE"
	},
	[MTD_HMRC_ERR_RULE_DUPLICATE_PERIOD] = {
		.str = "RULE_DUPLICATE_PERIOD"
	},
	[MTD_HMRC_ERR_RULE_DUPLICATE_SUBMISSION] = {
		.str = "RULE_DUPLICATE_SUBMISSION"
	},
	[MTD_HMRC_ERR_RULE_DUPLICATED_PPD_SUBMISSION_ID] = {
		.str = "RULE_DUPLICATED_PPD_SUBMISSION_ID"
	},
	[MTD_HMRC_ERR_RULE_EARLY_SUBMISSION] = {
		.str = "RULE_EARLY_SUBMISSION"
	},
	[MTD_HMRC_ERR_RULE_END_DATE_BEFORE_START_DATE] = {
		.str = "RULE_END_DATE_BEFORE_START_DATE"
	},
	[MTD_HMRC_ERR_RULE_END_DATE_BEFORE_TAX_YEAR_START] = {
		.str = "RULE_END_DATE_BEFORE_TAX_YEAR_START"
	},
	[MTD_HMRC_ERR_RULE_FHL_PRIVATE_USE_ADJUSTMENT] = {
		.str = "RULE_FHL_PRIVATE_USE_ADJUSTMENT"
	},
	[MTD_HMRC_ERR_RULE_FINAL_DECLARATION_RECEIVED] = {
		.str = "RULE_FINAL_DECLARATION_RECEIVED"
	},
	[MTD_HMRC_ERR_RULE_FROM_DATE_NOT_SUPPORTED] = {
		.str = "RULE_FROM_DATE_NOT_SUPPORTED"
	},
	[MTD_HMRC_ERR_RULE_GAIN_AFTER_RELIEF_LOSS_AFTER_RELIEF] = {
		.str = "RULE_GAIN_AFTER_RELIEF_LOSS_AFTER_RELIEF"
	},
	[MTD_HMRC_ERR_RULE_GAIN_LOSS] = {
		.str = "RULE_GAIN_LOSS"
	},
	[MTD_HMRC_ERR_RULE_GROSS_AMOUNT_PAID] = {
		.str = "RULE_GROSS_AMOUNT_PAID"
	},
	[MTD_HMRC_ERR_RULE_IGNORE_FORBIDDEN] = {
		.str = "RULE_IGNORE_FORBIDDEN"
	},
	[MTD_HMRC_ERR_RULE_INCOME_SOURCES_CHANGED] = {
		.str = "RULE_INCOME_SOURCES_CHANGED"
	},
	[MTD_HMRC_ERR_RULE_INCOME_SOURCES_INVALID] = {
		.str = "RULE_INCOME_SOURCES_INVALID"
	},
	[MTD_HMRC_ERR_RULE_INCORRECT_DISPOSAL_TYPE] = {
		.str = "RULE_INCORRECT_DISPOSAL_TYPE"
	},
	[MTD_HMRC_ERR_RULE_INCORRECT_OR_EMPTY_BODY_SUBMITTED] = {
		.str = "RULE_INCORRECT_OR_EMPTY_BODY_SUBMITTED"
	},
	[MTD_HMRC_ERR_RULE_INSOLVENT_TRADER] = {
		.str = "RULE_INSOLVENT_TRADER"
	},
	[MTD_HMRC_ERR_RULE_INVALID_REQUEST] = {
		.str = "RULE_INVALID_REQUEST"
	},
	[MTD_HMRC_ERR_RULE_INVALID_SEQUENCE_START] = {
		.str = "RULE_INVALID_SEQUENCE_START"
	},
	[MTD_HMRC_ERR_RULE_IS_ANNUAL_ALLOWANCE_REDUCED] = {
		.str = "RULE_IS_ANNUAL_ALLOWANCE_REDUCED"
	},
	[MTD_HMRC_ERR_RULE_LATE_SUBMISSION] = {
		.str = "RULE_LATE_SUBMISSION"
	},
	[MTD_HMRC_ERR_RULE_LOSS_AMOUNT] = {
		.str = "RULE_LOSS_AMOUNT"
	},
	[MTD_HMRC_ERR_RULE_LOSS_CLAIMS_MISSING] = {
		.str = "RULE_LOSS_CLAIMS_MISSING"
	},
	[MTD_HMRC_ERR_RULE_LOSSES_GREATER_THAN_GAIN] = {
		.str = "RULE_LOSSES_GREATER_THAN_GAIN"
	},
	[MTD_HMRC_ERR_RULE_LUMP_SUMS] = {
		.str = "RULE_LUMP_SUMS"
	},
	[MTD_HMRC_ERR_RULE_MISALIGNED_PERIOD] = {
		.str = "RULE_MISALIGNED_PERIOD"
	},
	[MTD_HMRC_ERR_RULE_MISMATCHED_END_DATE] = {
		.str = "RULE_MISMATCHED_END_DATE"
	},
	[MTD_HMRC_ERR_RULE_MISMATCHED_START_DATE] = {
		.str = "RULE_MISMATCHED_START_DATE"
	},
	[MTD_HMRC_ERR_RULE_NO_ACCOUNTING_PERIOD] = {
		.str = "RULE_NO_ACCOUNTING_PERIOD"
	},
	[MTD_HMRC_ERR_RULE_NO_ADJUSTMENTS_MADE] = {
		.str = "RULE_NO_ADJUSTMENTS_MADE"
	},
	[MTD_HMRC_ERR_RULE_NO_CHANGE] = {
		.str = "RULE_NO_CHANGE"
	},
	[MTD_HMRC_ERR_RULE_NO_INCOME_SUBMISSIONS_EXIST] = {
		.str = "RULE_NO_INCOME_SUBMISSIONS_EXIST"
	},
	[MTD_HMRC_ERR_RULE_NO_SUBMISSIONS_EXIST] = {
		.str = "RULE_NO_SUBMISSIONS_EXIST"
	},
	[MTD_HMRC_ERR_RULE_NON_FHL_PRIVATE_USE_ADJUSTMENT] = {
		.str = "RULE_NON_FHL_PRIVATE_USE_ADJUSTMENT"
	},
	[MTD_HMRC_ERR_RULE_NON_MATCHING_PERIOD] = {
		.str = "RULE_NON_MATCHING_PERIOD"
	},
	[MTD_HMRC_ERR_RULE_NOT_CONTIGUOUS_PERIOD] = {
		.str = "RULE_NOT_CONTIGUOUS_PERIOD"
	},
	[MTD_HMRC_ERR_RULE_NOT_FINALISED] = {
		.str = "RULE_NOT_FINALISED"
	},
	[MTD_HMRC_ERR_RULE_NOT_FOREIGN_PROPERTY] = {
		.str = "RULE_NOT_FOREIGN_PROPERTY"
	},
	[MTD_HMRC_ERR_RULE_NOT_SELF_EMPLOYMENT] = {
		.str = "RULE_NOT_SELF_EMPLOYMENT"
	},
	[MTD_HMRC_ERR_RULE_NOT_UK_PROPERTY] = {
		.str = "RULE_NOT_UK_PROPERTY"
	},
	[MTD_HMRC_ERR_RULE_OVER_CONSOLIDATED_EXPENSES_THRESHOLD] = {
		.str = "RULE_OVER_CONSOLIDATED_EXPENSES_THRESHOLD"
	},
	[MTD_HMRC_ERR_RULE_OVERLAPPING_PERIOD] = {
		.str = "RULE_OVERLAPPING_PERIOD"
	},
	[MTD_HMRC_ERR_RULE_PERIOD_NOT_ENDED] = {
		.str = "RULE_PERIOD_NOT_ENDED"
	},
	[MTD_HMRC_ERR_RULE_PERIODIC_DATA_INCOMPLETE] = {
		.str = "RULE_PERIODIC_DATA_INCOMPLETE"
	},
	[MTD_HMRC_ERR_RULE_PROPERTY_INCOME_ALLOWANCE_CLAIMED] = {
		.str = "RULE_PROPERTY_INCOME_ALLOWANCE_CLAIMED"
	},
	[MTD_HMRC_ERR_RULE_RANGE_INVALID] = {
		.str = "RULE_RANGE_INVALID"
	},
	[MTD_HMRC_ERR_RULE_RECENT_SUBMISSIONS_EXIST] = {
		.str = "RULE_RECENT_SUBMISSIONS_EXIST"
	},
	[MTD_HMRC_ERR_RULE_RESIDENCY_CHANGED] = {
		.str = "RULE_RESIDENCY_CHANGED"
	},
	[MTD_HMRC_ERR_RULE_RESULTING_VALUE_NOT_PERMITTED] = {
		.str = "RULE_RESULTING_VALUE_NOT_PERMITTED"
	},
	[MTD_HMRC_ERR_RULE_SELF_EMPLOYMENT_ADJUSTED] = {
		.str = "RULE_SELF_EMPLOYMENT_ADJUSTED"
	},
	[MTD_HMRC_ERR_RULE_SELF_EMPLOYMENT_ID] = {
		.str = "RULE_SELF_EMPLOYMENT_ID"
	},
	[MTD_HMRC_ERR_RULE_SEQUENCE_ORDER_BROKEN] = {
		.str = "RULE_SEQUENCE_ORDER_BROKEN"
	},
	[MTD_HMRC_ERR_RULE_SOURCE_INVALID] = {
		.str = "RULE_SOURCE_INVALID"
	},
	[MTD_HMRC_ERR_RULE_START_DATE_AFTER_TAX_YEAR_END] = {
		.str = "RULE_START_DATE_AFTER_TAX_YEAR_END"
	},
	[MTD_HMRC_ERR_RULE_SUBMISSION_FAILED] = {
		.str = "RULE_SUBMISSION_FAILED"
	},
	[MTD_HMRC_ERR_RULE_SUMMARY_STATUS_INVALID] = {
		.str = "RULE_SUMMARY_STATUS_INVALID"
	},
	[MTD_HMRC_ERR_RULE_SUMMARY_STATUS_SUPERSEDED] = {
		.str = "RULE_SUMMARY_STATUS_SUPERSEDED"
	},
	[MTD_HMRC_ERR_RULE_TAX_YEAR_NOT_ENDED] = {
		.str = "RULE_TAX_YEAR_NOT_ENDED"
	},
	[MTD_HMRC_ERR_RULE_TAX_YEAR_NOT_SUPPORTED] = {
		.str = "RULE_TAX_YEAR_NOT_SUPPORTED"
	},
	[MTD_HMRC_ERR_RULE_TAX_YEAR_RANGE_INVALID] = {
		.str = "RULE_TAX_YEAR_RANGE_INVALID"
	},
	[MTD_HMRC_ERR_RULE_TAX_YEAR_TOO_LONG] = {
		.str = "RULE_TAX_YEAR_TOO_LONG"
	},
	[MTD_HMRC_ERR_RULE_TO_DATE_BEFORE_FROM_DATE] = {
		.str = "RULE_TO_DATE_BEFORE_FROM_DATE"
	},
	[MTD_HMRC_ERR_RULE_TRADING_INCOME_ALLOWANCE_CLAIMED] = {
		.str = "RULE_TRADING_INCOME_ALLOWANCE_CLAIMED"
	},
	[MTD_HMRC_ERR_RULE_TYPE_OF_BUSINESS] = {
		.str = "RULE_TYPE_OF_BUSINESS"
	},
	[MTD_HMRC_ERR_RULE_TYPE_OF_BUSINESS_INCORRECT] = {
		.str = "RULE_TYPE_OF_BUSINESS_INCORRECT"
	},
	[MTD_HMRC_ERR_RULE_TYPE_OF_CLAIM_INVALID] = {
		.str = "RULE_TYPE_OF_CLAIM_INVALID"
	},
	[MTD_HMRC_ERR_RULE_UNALIGNED_DEDUCTIONS_PERIOD] = {
		.str = "RULE_UNALIGNED_DEDUCTIONS_PERIOD"
	},
	[MTD_HMRC_ERR_RULE_UNIGNORE_FORBIDDEN] = {
		.str = "RULE_UNIGNORE_FORBIDDEN"
	},
	[MTD_HMRC_ERR_RULE_UPDATE_FORBIDDEN] = {
		.str = "RULE_UPDATE_FORBIDDEN"
	},
	[MTD_HMRC_ERR_RULE_VOLUNTARY_CLASS2_CANNOT_BE_CHANGED] = {
		.str = "RULE_VOLUNTARY_CLASS2_CANNOT_BE_CHANGED"
	},
	[MTD_HMRC_ERR_RULE_VOLUNTARY_CLASS2_VALUE_INVALID] = {
		.str = "RULE_VOLUNTARY_CLASS2_VALUE_INVALID"
	},

	/*
	 * Self-Assessment API. This API is planned to be fully
	 * deprecated by March 2022. So group them altogether to
	 * facilitate easy removal.
	 */
	[MTD_HMRC_ERR_SA_AGENT_NOT_AUTHORIZED] = {
		.str = "AGENT_NOT_AUTHORIZED"
	},
	[MTD_HMRC_ERR_SA_AGENT_NOT_SUBSCRIBED] = {
		.str = "AGENT_NOT_SUBSCRIBED"
	},
	[MTD_HMRC_ERR_SA_BOTH_EXPENSES_SUPPLIED] = {
		.str = "BOTH_EXPENSES_SUPPLIED"
	},
	[MTD_HMRC_ERR_SA_CLIENT_NOT_SUBSCRIBED] = {
		.str = "CLIENT_NOT_SUBSCRIBED"
	},
	[MTD_HMRC_ERR_SA_DATE_NOT_IN_THE_PAST] = {
		.str = "DATE_NOT_IN_THE_PAST"
	},
	[MTD_HMRC_ERR_SA_FORMAT_ACCOUNT_NAME] = {
		.str = "FORMAT_ACCOUNT_NAME"
	},
	[MTD_HMRC_ERR_SA_FORMAT_GIFT_AID_FOLLOWING_YEAR_SPECIFIED_YEAR] = {
		.str = "FORMAT_GIFT_AID_FOLLOWING_YEAR_SPECIFIED_YEAR"
	},
	[MTD_HMRC_ERR_SA_FORMAT_GIFT_AID_NONUK_CHARITY_AMOUNT] = {
		.str = "FORMAT_GIFT_AID_NONUK_CHARITY_AMOUNT"
	},
	[MTD_HMRC_ERR_SA_FORMAT_GIFT_AID_NONUK_NAMES] = {
		.str = "FORMAT_GIFT_AID_NONUK_NAMES"
	},
	[MTD_HMRC_ERR_SA_FORMAT_GIFT_AID_ONE_OFF_SPECIFIED_YEAR] = {
		.str = "FORMAT_GIFT_AID_ONE_OFF_SPECIFIED_YEAR"
	},
	[MTD_HMRC_ERR_SA_FORMAT_GIFT_AID_SPECIFIED_YEAR] = {
		.str = "FORMAT_GIFT_AID_SPECIFIED_YEAR"
	},
	[MTD_HMRC_ERR_SA_FORMAT_GIFT_AID_SPECIFIED_YEAR_PREVIOUS_YEAR] = {
		.str = "FORMAT_GIFT_AID_SPECIFIED_YEAR_PREVIOUS_YEAR"
	},
	[MTD_HMRC_ERR_SA_FORMAT_GIFTS_INVESTMENTS_AMOUNT] = {
		.str = "FORMAT_GIFTS_INVESTMENTS_AMOUNT"
	},
	[MTD_HMRC_ERR_SA_FORMAT_GIFTS_LAND_BUILDINGS] = {
		.str = "FORMAT_GIFTS_LAND_BUILDINGS"
	},
	[MTD_HMRC_ERR_SA_FORMAT_GIFTS_NONUK_INVESTMENTS_NAMES] = {
		.str = "FORMAT_GIFTS_NONUK_INVESTMENTS_NAMES"
	},
	[MTD_HMRC_ERR_SA_FORMAT_GIFTS_SHARES_SECURITIES] = {
		.str = "FORMAT_GIFTS_SHARES_SECURITIES"
	},
	[MTD_HMRC_ERR_SA_FORMAT_OTHER_DIVIDENDS] = {
		.str = "FORMAT_OTHER_DIVIDENDS"
	},
	[MTD_HMRC_ERR_SA_FORMAT_SAVINGS_ACCOUNT_ID] = {
		.str = "FORMAT_SAVINGS_ACCOUNT_ID"
	},
	[MTD_HMRC_ERR_SA_FORMAT_TAXED_INTEREST] = {
		.str = "FORMAT_TAXED_INTEREST"
	},
	[MTD_HMRC_ERR_SA_FORMAT_UK_DIVIDENDS] = {
		.str = "FORMAT_UK_DIVIDENDS"
	},
	[MTD_HMRC_ERR_SA_FORMAT_UNTAXED_INTEREST] = {
		.str = "FORMAT_UNTAXED_INTEREST"
	},
	[MTD_HMRC_ERR_SA_INVALID_ACCOUNTING_PERIOD] = {
		.str = "INVALID_ACCOUNTING_PERIOD"
	},
	[MTD_HMRC_ERR_SA_INVALID_BOOLEAN_VALUE] = {
		.str = "INVALID_BOOLEAN_VALUE"
	},
	[MTD_HMRC_ERR_SA_INVALID_DATE] = {
		.str = "INVALID_DATE"
	},
	[MTD_HMRC_ERR_SA_INVALID_FIELD_FORMAT] = {
		.str = "INVALID_FIELD_FORMAT"
	},
	[MTD_HMRC_ERR_SA_INVALID_FIELD_LENGTH] = {
		.str = "INVALID_FIELD_LENGTH"
	},
	[MTD_HMRC_ERR_SA_INVALID_MONETARY_AMOUNT] = {
		.str = "INVALID_MONETARY_AMOUNT"
	},
	[MTD_HMRC_ERR_SA_INVALID_PERIOD] = {
		.str = "INVALID_PERIOD"
	},
	[MTD_HMRC_ERR_SA_INVALID_POSTCODE] = {
		.str = "INVALID_POSTCODE"
	},
	[MTD_HMRC_ERR_SA_INVALID_VALUE] = {
		.str = "INVALID_VALUE"
	},
	[MTD_HMRC_ERR_SA_MANDATORY_FIELD_MISSING] = {
		.str = "MANDATORY_FIELD_MISSING"
	},
	[MTD_HMRC_ERR_SA_MISALIGNED_PERIOD] = {
		.str = "MISALIGNED_PERIOD"
	},
	[MTD_HMRC_ERR_SA_MISSING_ACCOUNT_NAME] = {
		.str = "MISSING_ACCOUNT_NAME"
	},
	[MTD_HMRC_ERR_SA_NINO_INVALID] = {
		.str = "NINO_INVALID"
	},
	[MTD_HMRC_ERR_SA_NO_INCOMES_AND_EXPENSES] = {
		.str = "NO_INCOMES_AND_EXPENSES"
	},
	[MTD_HMRC_ERR_SA_NOT_ALLOWED_CONSOLIDATED_EXPENSES] = {
		.str = "NOT_ALLOWED_CONSOLIDATED_EXPENSES"
	},
	[MTD_HMRC_ERR_SA_NOT_CONTIGUOUS_PERIOD] = {
		.str = "NOT_CONTIGUOUS_PERIOD"
	},
	[MTD_HMRC_ERR_SA_NOT_OVER_STATE_PENSION] = {
		.str = "NOT_OVER_STATE_PENSION"
	},
	[MTD_HMRC_ERR_SA_NOT_UNDER_16] = {
		.str = "NOT_UNDER_16"
	},
	[MTD_HMRC_ERR_SA_OVERLAPPING_PERIOD] = {
		.str = "OVERLAPPING_PERIOD"
	},
	[MTD_HMRC_ERR_SA_RULE_DUPLICATE_ACCOUNT_NAME] = {
		.str = "RULE_DUPLICATE_ACCOUNT_NAME"
	},
	[MTD_HMRC_ERR_SA_RULE_EMPTY_GIFTS_OR_GIFT_AID] = {
		.str = "RULE_EMPTY_GIFTS_OR_GIFT_AID"
	},
	[MTD_HMRC_ERR_SA_RULE_GIFT_AID_NONUK_AMOUNT_WITHOUT_NAMES] = {
		.str = "RULE_GIFT_AID_NONUK_AMOUNT_WITHOUT_NAMES"
	},
	[MTD_HMRC_ERR_SA_RULE_GIFT_AID_NONUK_NAMES_WITHOUT_AMOUNT] = {
		.str = "RULE_GIFT_AID_NONUK_NAMES_WITHOUT_AMOUNT"
	},
	[MTD_HMRC_ERR_SA_RULE_GIFTS_NONUK_INVESTMENTS_AMOUNT_WITHOUT_NAMES] = {
		.str = "RULE_GIFTS_NONUK_INVESTMENTS_AMOUNT_WITHOUT_NAMES"
	},
	[MTD_HMRC_ERR_SA_RULE_GIFTS_NONUK_INVESTMENTS_NAMES_WITHOUT_AMOUNT] = {
		.str = "RULE_GIFTS_NONUK_INVESTMENTS_NAMES_WITHOUT_AMOUNT"
	},
	[MTD_HMRC_ERR_SA_RULE_MAXIMUM_SAVINGS_ACCOUNTS_LIMIT] = {
		.str = "RULE_MAXIMUM_SAVINGS_ACCOUNTS_LIMIT"
	},
	[MTD_HMRC_ERR_SA_RULE_TAX_YEAR_RANGE_EXCEEDED] = {
		.str = "RULE_TAX_YEAR_RANGE_EXCEEDED"
	},
	[MTD_HMRC_ERR_SA_START_DATE_INVALID] = {
		.str = "START_DATE_INVALID"
	},
	[MTD_HMRC_ERR_SA_TAX_YEAR_INVALID] = {
		.str = "TAX_YEAR_INVALID"
	},

	/* Generic top-level errors */
	[MTD_HMRC_ERR_BUSINESS_ERROR] = {
		.str = "BUSINESS_ERROR"
	},
	[MTD_HMRC_ERR_INVALID_REQUEST] = {
		.str = "INVALID_REQUEST"
	},

	[MTD_HMRC_ERR_UNKNOWN] = {
		.str = "MTD_HMRC_ERR_UNKNOWN"
	}
};

enum mtd_hmrc_error mtd_hmrc_error(const char *json)
{
	json_t *jarray;
	json_t *root;
	json_t *result;
	json_t *code_obj;
	json_t *ecode_obj = NULL;
	json_t *errors;
	const char *code;
	int i;
	enum mtd_hmrc_error err = MTD_HMRC_ERR_UNKNOWN;

	jarray = json_loads(json, 0, NULL);
	root = json_array_get(jarray, json_array_size(jarray) - 1);
	result = json_object_get(root, "result");
	errors = json_object_get(root, "errors");
	if (errors && json_array_size(errors) > 1) {
		err = MTD_HMRC_ERR_MULTIPLE;
		goto out_free;
	} else if (errors) {
		ecode_obj = json_object_get(errors, "code");
		code_obj = ecode_obj;
	}

	/*
	 * You can get 1 or more HMRC errors returned from endpoints.
	 *
	 * Normally a single error would just be in the top level
	 * 'result' and multiple errors would be contained in an
	 * 'errors' array.
	 *
	 * However you can also get an errors array that only contains
	 * a single error and still have a top level error.
	 *
	 * Whether there's just a single error or multiple errors in
	 * the errors array, that will be the more specific error. So
	 * we want to check for that error first then fallback to the
	 * top level error.
	 *
	 * The reason for two separate loops for the two codes is so
	 * that we can put in generic codes like 'INVALID_REQUEST' &
	 * 'BUSINESS_ERROR' and we will only use them if we didn't
	 * find a more specific error code first.
	 */
	if (!ecode_obj)
		code_obj = json_object_get(result, "code");
	if (!code_obj)
		goto out_free;

	code = json_string_value(code_obj);
	for (i = 0; i < MTD_HMRC_ERR_UNKNOWN; i++) {
		if (strcmp(mtd_hmrc_err_map[i].str, code) != 0)
			continue;

		err = i;
		goto out_free;
	}

	if (!ecode_obj)
		goto out_free;

	code_obj = json_object_get(result, "code");
	code = json_string_value(code_obj);
	for (i = 0; i < MTD_HMRC_ERR_UNKNOWN; i++) {
		if (strcmp(mtd_hmrc_err_map[i].str, code) != 0)
			continue;

		err = i;
		break;
	}

out_free:
	json_decref(jarray);

	return err;
}
