/* SPDX-License-Identifier: LGPL-2.1 */

/*
 * mtd-hmrc-err.c - Make Tax Digital API Errors
 *
 * Copyright (C) 2020 - 2025	Andrew Clayton <ac@sigsegv.uk>
 */

#define _GNU_SOURCE

#include <stdlib.h>
#include <string.h>

#include <jansson.h>

#include "mtd.h"

#define ERR_MAP_ENT(err)	[MTD_HMRC_ERR_##err] = { .str = #err }

static const struct {
	const char *str;
} mtd_hmrc_err_map[] = {
	[MTD_HMRC_ERR_MULTIPLE] = {
		.str = "MTD_HMRC_ERR_MULTIPLE"
	},

	ERR_MAP_ENT(CHARGE_REFERENCE_INVALID),

	ERR_MAP_ENT(CLIENT_OR_AGENT_NOT_AUTHORISED),

	ERR_MAP_ENT(DATE_FROM_INVALID),
	ERR_MAP_ENT(DATE_RANGE_INVALID),
	ERR_MAP_ENT(DATE_RANGE_TOO_LARGE),
	ERR_MAP_ENT(DATE_TO_INVALID),

	ERR_MAP_ENT(DUPLICATE_SUBMISSION),
	ERR_MAP_ENT(DUPLICATE_SUBMITTED_ON),

	ERR_MAP_ENT(FORMAT_ACCOUNT_NAME),
	ERR_MAP_ENT(FORMAT_BENEFIT_ID),
	ERR_MAP_ENT(FORMAT_BENEFIT_TYPE),
	ERR_MAP_ENT(FORMAT_BUSINESS_ID),
	ERR_MAP_ENT(FORMAT_BUSINESS_INCOME_2_YEARS_PRIOR),
	ERR_MAP_ENT(FORMAT_CALC_ID),
	ERR_MAP_ENT(FORMAT_CALCULATE_ACCRUED_INTEREST),
	ERR_MAP_ENT(FORMAT_CALCULATION_ID),
	ERR_MAP_ENT(FORMAT_CALCULATION_TYPE),
	ERR_MAP_ENT(FORMAT_CESSATION_DATE),
	ERR_MAP_ENT(FORMAT_CHARGE_REFERENCE),
	ERR_MAP_ENT(FORMAT_CHECKPOINT_ID),
	ERR_MAP_ENT(FORMAT_CLASS_4_EXEMPTION_REASON),
	ERR_MAP_ENT(FORMAT_CLASS_OF_SHARES_ACQUIRED),
	ERR_MAP_ENT(FORMAT_CLASS_OF_SHARES_AWARDED),
	ERR_MAP_ENT(FORMAT_COMPANY_NAME),
	ERR_MAP_ENT(FORMAT_COMPANY_NUMBER),
	ERR_MAP_ENT(FORMAT_COUNTRY_CODE),
	ERR_MAP_ENT(FORMAT_CUSTOMER_PAYMENT_INFORMATION),
	ERR_MAP_ENT(FORMAT_CUSTOMER_REF),
	ERR_MAP_ENT(FORMAT_CUSTOMER_REFERENCE),
	ERR_MAP_ENT(FORMAT_DATE),
	ERR_MAP_ENT(FORMAT_DEDUCTIONS_FROM_DATE),
	ERR_MAP_ENT(FORMAT_DEDUCTIONS_TO_DATE),
	ERR_MAP_ENT(FORMAT_DIRECTORSHIP_CEASED_DATE),
	ERR_MAP_ENT(FORMAT_DOC_NUMBER),
	ERR_MAP_ENT(FORMAT_DOUBLE_TAXATION_ARTICLE),
	ERR_MAP_ENT(FORMAT_DOUBLE_TAXATION_TREATY),
	ERR_MAP_ENT(FORMAT_EMPLOYER_NAME),
	ERR_MAP_ENT(FORMAT_EMPLOYER_REF),
	ERR_MAP_ENT(FORMAT_EMPLOYER_REFERENCE),
	ERR_MAP_ENT(FORMAT_EMPLOYMENT_ID),
	ERR_MAP_ENT(FORMAT_END_DATE),
	ERR_MAP_ENT(FORMAT_EVENT),
	ERR_MAP_ENT(FORMAT_FINAL_DECLARATION),
	ERR_MAP_ENT(FORMAT_FROM_DATE),
	ERR_MAP_ENT(FORMAT_FUTURE_YEARS),
	ERR_MAP_ENT(FORMAT_HISTORY),
	ERR_MAP_ENT(FORMAT_ID),
	ERR_MAP_ENT(FORMAT_INCLUDE_ESTIMATED_CHARGES),
	ERR_MAP_ENT(FORMAT_INCLUDE_LOCKS),
	ERR_MAP_ENT(FORMAT_LOSS_ID),
	ERR_MAP_ENT(FORMAT_NAME_OF_SHIP),
	ERR_MAP_ENT(FORMAT_NINO),
	ERR_MAP_ENT(FORMAT_ONLY_OPEN_ITEMS),
	ERR_MAP_ENT(FORMAT_PAYMENT_LOT),
	ERR_MAP_ENT(FORMAT_PAYMENT_LOT_ITEM),
	ERR_MAP_ENT(FORMAT_PAYROLL_ID),
	ERR_MAP_ENT(FORMAT_PENSION_SCHEME_TAX_REFERENCE),
	ERR_MAP_ENT(FORMAT_PERIOD_ID),
	ERR_MAP_ENT(FORMAT_PROVIDER_NAME),
	ERR_MAP_ENT(FORMAT_PROVIDERS_ADDRESS),
	ERR_MAP_ENT(FORMAT_QOPS_REF),
	ERR_MAP_ENT(FORMAT_REMOVE_PAYMENT_ON_ACCOUNT),
	ERR_MAP_ENT(FORMAT_REPORT_ID),
	ERR_MAP_ENT(FORMAT_SAVINGS_ACCOUNT_ID),
	ERR_MAP_ENT(FORMAT_SCHEME_PLAN_TYPE),
	ERR_MAP_ENT(FORMAT_SF74_REF),
	ERR_MAP_ENT(FORMAT_SOURCE),
	ERR_MAP_ENT(FORMAT_SPOUSE_OR_CIVIL_PARTNERS_DATE_OF_BIRTH),
	ERR_MAP_ENT(FORMAT_SPOUSE_OR_CIVIL_PARTNERS_FIRST_NAME),
	ERR_MAP_ENT(FORMAT_SPOUSE_OR_CIVIL_PARTNERS_NINO),
	ERR_MAP_ENT(FORMAT_SPOUSE_OR_CIVIL_PARTNERS_SURNAME),
	ERR_MAP_ENT(FORMAT_SRN_INVALID),
	ERR_MAP_ENT(FORMAT_START_DATE),
	ERR_MAP_ENT(FORMAT_STATUS),
	ERR_MAP_ENT(FORMAT_STATUS_REASON),
	ERR_MAP_ENT(FORMAT_STRING),
	ERR_MAP_ENT(FORMAT_SUBMISSION_ID),
	ERR_MAP_ENT(FORMAT_SUBMITTED_ON),
	ERR_MAP_ENT(FORMAT_TAX_SOURCE),
	ERR_MAP_ENT(FORMAT_TAX_YEAR),
	ERR_MAP_ENT(FORMAT_TO_DATE),
	ERR_MAP_ENT(FORMAT_TRANSACTION_ID),
	ERR_MAP_ENT(FORMAT_TYPE_OF_BUSINESS),
	ERR_MAP_ENT(FORMAT_TYPE_OF_LOSS),
	ERR_MAP_ENT(FORMAT_VALUE),

	ERR_MAP_ENT(INVALID_CREDENTIALS),
	ERR_MAP_ENT(INVALID_DATE_FROM),
	ERR_MAP_ENT(INVALID_DATE_RANGE),
	ERR_MAP_ENT(INVALID_DATE_TO),
	ERR_MAP_ENT(INVALID_MONETARY_AMOUNT),
	ERR_MAP_ENT(INVALID_NUMERIC_VALUE),
	ERR_MAP_ENT(INVALID_STATUS),
	ERR_MAP_ENT(INVALID_TAX_YEAR_PARAMETER),

	ERR_MAP_ENT(MATCHING_CALCULATION_ID_NOT_FOUND),
	ERR_MAP_ENT(MATCHING_RESOURCE_NOT_FOUND),

	ERR_MAP_ENT(MISSING_FROM_DATE),
	ERR_MAP_ENT(MISSING_OFF_PAYROLL_WORKER),
	ERR_MAP_ENT(MISSING_PAYMENT_LOT),
	ERR_MAP_ENT(MISSING_PAYMENT_LOT_ITEM),
	ERR_MAP_ENT(MISSING_TO_DATE),
	ERR_MAP_ENT(MISSING_TYPE_OF_BUSINESS),

	ERR_MAP_ENT(NOT_ALLOWED_OFF_PAYROLL_WORKER),
	ERR_MAP_ENT(NOT_FINALISED),
	ERR_MAP_ENT(NOT_FOUND),

	ERR_MAP_ENT(PERIOD_KEY_INVALID),

	ERR_MAP_ENT(RANGE_TO_DATE_BEFORE_FROM_DATE),

	ERR_MAP_ENT(RULE_ACCOUNTING_PERIOD_NOT_ENDED),
	ERR_MAP_ENT(RULE_ACCOUNTING_PERIOD_NOT_SUPPORTED),
	ERR_MAP_ENT(RULE_ACTIVE_MARRIAGE_ALLOWANCE_CLAIM),
	ERR_MAP_ENT(RULE_ADVANCE_SUBMISSION_REQUIRES_PERIOD_END_DATE),
	ERR_MAP_ENT(RULE_ALLOWANCE_NOT_SUPPORTED),
	ERR_MAP_ENT(RULE_ALREADY_ADJUSTED),
	ERR_MAP_ENT(RULE_ALREADY_OPTED_IN),
	ERR_MAP_ENT(RULE_ALREADY_OPTED_OUT),
	ERR_MAP_ENT(RULE_BENEFIT_TYPE_EXISTS),
	ERR_MAP_ENT(RULE_BFL_NOT_SUPPORTED_FOR_FHL_PROPERTIES),
	ERR_MAP_ENT(RULE_BOTH_ALLOWANCES_SUPPLIED),
	ERR_MAP_ENT(RULE_BOTH_EXPENSES_SUPPLIED),
	ERR_MAP_ENT(RULE_BOTH_PROPERTIES_SUPPLIED),
	ERR_MAP_ENT(RULE_BUILDING_NAME_NUMBER),
	ERR_MAP_ENT(RULE_BUSINESS_ID_NOT_FOUND),
	ERR_MAP_ENT(RULE_BUSINESS_ID_STATE_CONFLICT),
	ERR_MAP_ENT(RULE_BUSINESS_INCOME_PERIOD_RESTRICTION),
	ERR_MAP_ENT(RULE_BUSINESS_PARTNER_NOT_EXIST),
	ERR_MAP_ENT(RULE_BUSINESS_VALIDATION_FAILURE),
	ERR_MAP_ENT(RULE_CALCULATION_IN_PROGRESS),
	ERR_MAP_ENT(RULE_CALCULATION_TYPE_NOT_ALLOWED),
	ERR_MAP_ENT(RULE_CESSATION_DATE),
	ERR_MAP_ENT(RULE_CESSATION_DATE_BEFORE_START_DATE),
	ERR_MAP_ENT(RULE_CESSATION_DATE_BEFORE_TAX_YEAR_START),
	ERR_MAP_ENT(RULE_COST_OF_MATERIALS),
	ERR_MAP_ENT(RULE_COUNTRY_CODE),
	ERR_MAP_ENT(RULE_CUSTOM_EMPLOYMENT),
	ERR_MAP_ENT(RULE_DATE_CEASED),
	ERR_MAP_ENT(RULE_DATE_RANGE_INVALID),
	ERR_MAP_ENT(RULE_DECEASED_RECIPIENT),
	ERR_MAP_ENT(RULE_DECLARATION_NOT_RECEIVED),
	ERR_MAP_ENT(RULE_DEDUCTIONS_AMOUNT),
	ERR_MAP_ENT(RULE_DEDUCTIONS_DATE_RANGE_INVALID),
	ERR_MAP_ENT(RULE_DELETE_AFTER_FINAL_DECLARATION),
	ERR_MAP_ENT(RULE_DELETE_FORBIDDEN),
	ERR_MAP_ENT(RULE_DIRECTORSHIP_CEASED_DATE),
	ERR_MAP_ENT(RULE_DUPLICATE_COUNTRY_CODE),
	ERR_MAP_ENT(RULE_DUPLICATE_ID_NOT_ALLOWED),
	ERR_MAP_ENT(RULE_DUPLICATE_PERIOD),
	ERR_MAP_ENT(RULE_DUPLICATE_SUBMISSION),
	ERR_MAP_ENT(RULE_EARLY_DATA_SUBMISSION_NOT_ACCEPTED),
	ERR_MAP_ENT(RULE_ELECTION_PERIOD_NOT_EXPIRED),
	ERR_MAP_ENT(RULE_END_DATE),
	ERR_MAP_ENT(RULE_END_DATE_BEFORE_START_DATE),
	ERR_MAP_ENT(RULE_END_DATE_BEFORE_TAX_YEAR_START),
	ERR_MAP_ENT(RULE_END_DATE_NOT_ALIGNED_WITH_REPORTING_TYPE),
	ERR_MAP_ENT(RULE_FINAL_DECLARATION_IN_PROGRESS),
	ERR_MAP_ENT(RULE_FINAL_DECLARATION_RECEIVED),
	ERR_MAP_ENT(RULE_FINAL_DECLARATION_TAX_YEAR),
	ERR_MAP_ENT(RULE_FROM_DATE_NOT_SUPPORTED),
	ERR_MAP_ENT(RULE_GROSS_AMOUNT_PAID),
	ERR_MAP_ENT(RULE_IGNORE_FORBIDDEN),
	ERR_MAP_ENT(RULE_INCOME_SOURCES_CHANGED),
	ERR_MAP_ENT(RULE_INCOME_SOURCES_INVALID),
	ERR_MAP_ENT(RULE_INCONSISTENT_QUERY_PARAMS),
	ERR_MAP_ENT(RULE_INCORRECT_GOV_TEST_SCENARIO),
	ERR_MAP_ENT(RULE_INCORRECT_OR_EMPTY_BODY_SUBMITTED),
	ERR_MAP_ENT(RULE_INSOLVENT_TRADER),
	ERR_MAP_ENT(RULE_INVALID_DATE_RANGE),
	ERR_MAP_ENT(RULE_INVALID_REQUEST),
	ERR_MAP_ENT(RULE_INVALID_SUBMISSION_PENSION_SCHEME),
	ERR_MAP_ENT(RULE_IS_ANNUAL_ALLOWANCE_REDUCED),
	ERR_MAP_ENT(RULE_ITSA_CONTRACT_OBJECT_NOT_EXIST),
	ERR_MAP_ENT(RULE_LUMP_SUMS),
	ERR_MAP_ENT(RULE_MISALIGNED_PERIOD),
	ERR_MAP_ENT(RULE_MISSING_CLOSE_COMPANY),
	ERR_MAP_ENT(RULE_MISSING_CLOSE_COMPANY_DETAILS),
	ERR_MAP_ENT(RULE_MISSING_SUBMISSION_DATES),
	ERR_MAP_ENT(RULE_NO_ACCOUNTING_DATE_FOUND),
	ERR_MAP_ENT(RULE_NO_ACCOUNTING_PERIOD),
	ERR_MAP_ENT(RULE_NO_CHANGE),
	ERR_MAP_ENT(RULE_NO_INCOME_SUBMISSIONS_EXIST),
	ERR_MAP_ENT(RULE_NOT_ALLOWED_CONSOLIDATED_EXPENSES),
	ERR_MAP_ENT(RULE_NOT_CONTIGUOUS_PERIOD),
	ERR_MAP_ENT(RULE_OBLIGATIONS_NOT_MET),
	ERR_MAP_ENT(RULE_OUTSIDE_AMENDMENT_WINDOW),
	ERR_MAP_ENT(RULE_OVER_CONSOLIDATED_EXPENSES_THRESHOLD),
	ERR_MAP_ENT(RULE_OVERLAPPING_PERIOD),
	ERR_MAP_ENT(RULE_PERIODS_OF_ACCOUNT),
	ERR_MAP_ENT(RULE_PREMATURE_FINALISATION),
	ERR_MAP_ENT(RULE_PROPERTY_INCOME_ALLOWANCE),
	ERR_MAP_ENT(RULE_PROPERTY_INCOME_ALLOWANCE_CLAIMED),
	ERR_MAP_ENT(RULE_QUARTERLY_PERIOD_UPDATING),
	ERR_MAP_ENT(RULE_RECENT_SUBMISSIONS_EXIST),
	ERR_MAP_ENT(RULE_REQUEST_CANNOT_BE_FULFILLED),
	ERR_MAP_ENT(RULE_RESIDENCY_CHANGED),
	ERR_MAP_ENT(RULE_RESULTING_VALUE_NOT_PERMITTED),
	ERR_MAP_ENT(RULE_START_DATE),
	ERR_MAP_ENT(RULE_START_AND_END_DATE_NOT_ALLOWED),
	ERR_MAP_ENT(RULE_START_DATE_AFTER_TAX_YEAR_END),
	ERR_MAP_ENT(RULE_START_DATE_NOT_ALIGNED_TO_COMMENCEMENT_DATE),
	ERR_MAP_ENT(RULE_START_DATE_NOT_ALIGNED_WITH_REPORTING_TYPE),
	ERR_MAP_ENT(RULE_SOURCE_INVALID),
	ERR_MAP_ENT(RULE_SUBMISSION_END_DATE_CANNOT_MOVE_BACKWARDS),
	ERR_MAP_ENT(RULE_SUBMISSION_FAILED),
	ERR_MAP_ENT(RULE_SUMMARY_STATUS_INVALID),
	ERR_MAP_ENT(RULE_SUMMARY_STATUS_SUPERSEDED),
	ERR_MAP_ENT(RULE_TAX_YEAR_NOT_ENDED),
	ERR_MAP_ENT(RULE_TAX_YEAR_NOT_SUPPORTED),
	ERR_MAP_ENT(RULE_TAX_YEAR_RANGE_EXCEEDED),
	ERR_MAP_ENT(RULE_TAX_YEAR_RANGE_INVALID),
	ERR_MAP_ENT(RULE_TO_DATE_BEFORE_FROM_DATE),
	ERR_MAP_ENT(RULE_TRADING_INCOME_ALLOWANCE_CLAIMED),
	ERR_MAP_ENT(RULE_TYPE_OF_BUSINESS_INCORRECT),
	ERR_MAP_ENT(RULE_UNALIGNED_CESSATION_TAX_YEAR),
	ERR_MAP_ENT(RULE_UNALIGNED_DEDUCTIONS_PERIOD),
	ERR_MAP_ENT(RULE_UNIGNORE_FORBIDDEN),
	ERR_MAP_ENT(RULE_UPDATE_FORBIDDEN),
	ERR_MAP_ENT(RULE_VOLUNTARY_CLASS2_CANNOT_BE_CHANGED),
	ERR_MAP_ENT(RULE_VOLUNTARY_CLASS2_VALUE_INVALID),
	ERR_MAP_ENT(RULE_WRONG_TPA_AMOUNT_SUBMITTED),
	ERR_MAP_ENT(RULE_ZERO_ADJUSTMENTS_INVALID),

	ERR_MAP_ENT(TAX_PERIOD_NOT_ENDED),

	ERR_MAP_ENT(VAT_NET_VALUE),
	ERR_MAP_ENT(VAT_TOTAL_VALUE),

	ERR_MAP_ENT(VRN_INVALID),

	/* Generic top-level errors */
	ERR_MAP_ENT(BUSINESS_ERROR),
	ERR_MAP_ENT(INVALID_REQUEST),

	[MTD_HMRC_ERR_UNKNOWN] = {
		.str = "MTD_HMRC_ERR_UNKNOWN"
	}
};

void mtd_hmrc_free_error(struct mtd_hmrc_err *mhe)
{
	while (mhe) {
		struct mtd_hmrc_err *p;

		p = mhe;
		mhe = mhe->next;

		free((char *)p->code);
		free((char *)p->msg);
		free(p);
	}
}

static enum mtd_hmrc_error lookup_hmrc_error(const char *code)
{
	for (int i = 0; i < MTD_HMRC_ERR_UNKNOWN; i++) {
		if (strcmp(mtd_hmrc_err_map[i].str, code) == 0)
			return i;
	}

	return MTD_HMRC_ERR_UNKNOWN;
}


int mtd_hmrc_get_error(const char *json, struct mtd_hmrc_err **mhe)
{
	json_t *jarray;
	json_t *root;
	json_t *result;
	json_t *code_obj;
	json_t *msg_obj;
	json_t *errors;
	json_t *error;
	size_t index;
	const char *code;
	struct mtd_hmrc_err *mhep;

	jarray = json_loads(json, 0, NULL);
	root = json_array_get(jarray, json_array_size(jarray) - 1);
	result = json_object_get(root, "result");
	errors = json_object_get(result, "errors");

	*mhe = calloc(1, sizeof(struct mtd_hmrc_err));
	if (!*mhe)
		return MTD_ERR_OS;

	if (!errors) {
		code_obj = json_object_get(result, "code");
		if (!code_obj)
			goto out_err_free;

		code = json_string_value(code_obj);

		(*mhe)->error = lookup_hmrc_error(code);
		(*mhe)->code = strdup(code);

		msg_obj = json_object_get(result, "message");
		if (msg_obj)
			(*mhe)->msg = strdup(json_string_value(msg_obj));
		else
			(*mhe)->msg = strdup("");

		return MTD_ERR_NONE;
	}

	mhep = *mhe;

	json_array_foreach(errors, index, error) {
		code_obj = json_object_get(error, "code");
		if (!code_obj)
			continue;

		if (index > 0) {
			(*mhe)->next = calloc(1, sizeof(struct mtd_hmrc_err));
			if (!(*mhe)->next)
				goto out_err_free;

			*mhe = (*mhe)->next;
		}

		code = json_string_value(code_obj);

		(*mhe)->error = lookup_hmrc_error(code);
		(*mhe)->code = strdup(code);

		msg_obj = json_object_get(error, "message");
		if (msg_obj)
			(*mhe)->msg = strdup(json_string_value(msg_obj));
		else
			(*mhe)->msg = strdup("");
	}

	*mhe = mhep;

	return MTD_ERR_NONE;

out_err_free:
	mtd_hmrc_free_error(*mhe);
	*mhe = NULL;

	return MTD_ERR_OS;
}
