/* SPDX-License-Identifier: LGPL-2.1 */

/*
 * mtd-hmrc-err.c - Make Tax Digital API Errors
 *
 * Copyright (C) 2020 - 2025	Andrew Clayton <ac@sigsegv.uk>
 */

#define _GNU_SOURCE

#include <string.h>

#include <jansson.h>

#include "mtd.h"

#define ERR_MAP_ENT(err)	[MTD_HMRC_ERR_##err] = { .str = #err }

static const struct {
	const char *str;
} mtd_hmrc_err_map[] = {
	[MTD_HMRC_ERR_MULTIPLE] = {
		.str = "MTD_HMRC_ERR_MULTIPLE"
	},

	ERR_MAP_ENT(CLIENT_OR_AGENT_NOT_AUTHORISED),

	ERR_MAP_ENT(END_OF_YEAR_ESTIMATE_NOT_PRESENT),

	ERR_MAP_ENT(FORMAT_ADJUSTED_STATUS),
	ERR_MAP_ENT(FORMAT_ADJUSTMENT_VALUE),
	ERR_MAP_ENT(FORMAT_ASSET_DESCRIPTION),
	ERR_MAP_ENT(FORMAT_ASSET_TYPE),
	ERR_MAP_ENT(FORMAT_BENEFIT_ID),
	ERR_MAP_ENT(FORMAT_BENEFIT_TYPE),
	ERR_MAP_ENT(FORMAT_BSAS_ID),
	ERR_MAP_ENT(FORMAT_BUSINESS_ID),
	ERR_MAP_ENT(FORMAT_CALC_ID),
	ERR_MAP_ENT(FORMAT_CESSATION_DATE),
	ERR_MAP_ENT(FORMAT_CLAIM_ID),
	ERR_MAP_ENT(FORMAT_CLAIM_OR_ELECTION_CODES),
	ERR_MAP_ENT(FORMAT_CLAIM_TYPE),
	ERR_MAP_ENT(FORMAT_CLASS_OF_SHARES_ACQUIRED),
	ERR_MAP_ENT(FORMAT_CLASS_OF_SHARES_AWARDED),
	ERR_MAP_ENT(FORMAT_COUNTRY_CODE),
	ERR_MAP_ENT(FORMAT_CUSTOMER_REF),
	ERR_MAP_ENT(FORMAT_CUSTOMER_REFERENCE),
	ERR_MAP_ENT(FORMAT_DATE),
	ERR_MAP_ENT(FORMAT_DATE_OF_INVESTMENT),
	ERR_MAP_ENT(FORMAT_DEDUCTIONS_FROM_DATE),
	ERR_MAP_ENT(FORMAT_DEDUCTIONS_TO_DATE),
	ERR_MAP_ENT(FORMAT_DOUBLE_TAXATION_ARTICLE),
	ERR_MAP_ENT(FORMAT_DOUBLE_TAXATION_TREATY),
	ERR_MAP_ENT(FORMAT_EMPLOYER_NAME),
	ERR_MAP_ENT(FORMAT_EMPLOYER_REF),
	ERR_MAP_ENT(FORMAT_EMPLOYER_REFERENCE),
	ERR_MAP_ENT(FORMAT_EMPLOYMENT_ID),
	ERR_MAP_ENT(FORMAT_END_DATE),
	ERR_MAP_ENT(FORMAT_EVENT),
	ERR_MAP_ENT(FORMAT_FINALISED),
	ERR_MAP_ENT(FORMAT_FROM_DATE),
	ERR_MAP_ENT(FORMAT_ID),
	ERR_MAP_ENT(FORMAT_INCOME_SOURCE),
	ERR_MAP_ENT(FORMAT_LENDER_NAME),
	ERR_MAP_ENT(FORMAT_LOSS_AMOUNT),
	ERR_MAP_ENT(FORMAT_LOSS_ID),
	ERR_MAP_ENT(FORMAT_NAME),
	ERR_MAP_ENT(FORMAT_NAME_BUSINESS),
	ERR_MAP_ENT(FORMAT_NAME_EX_SPOUSE),
	ERR_MAP_ENT(FORMAT_NAME_OF_SHIP),
	ERR_MAP_ENT(FORMAT_NATURE_OF_TRADE),
	ERR_MAP_ENT(FORMAT_NINO),
	ERR_MAP_ENT(FORMAT_PAYMENT_ID),
	ERR_MAP_ENT(FORMAT_PAYROLL_ID),
	ERR_MAP_ENT(FORMAT_PENSION_SCHEME_TAX_REFERENCE),
	ERR_MAP_ENT(FORMAT_PPD_SUBMISSION_ID),
	ERR_MAP_ENT(FORMAT_PROVIDER_NAME),
	ERR_MAP_ENT(FORMAT_PROVIDERS_ADDRESS),
	ERR_MAP_ENT(FORMAT_QOPS_REF),
	ERR_MAP_ENT(FORMAT_SCHEME_PLAN_TYPE),
	ERR_MAP_ENT(FORMAT_SELF_EMPLOYMENT_ID),
	ERR_MAP_ENT(FORMAT_SEQUENCE),
	ERR_MAP_ENT(FORMAT_SF74_REF),
	ERR_MAP_ENT(FORMAT_SOURCE),
	ERR_MAP_ENT(FORMAT_SPOUSE_OR_CIVIL_PARTNERS_DATE_OF_BIRTH),
	ERR_MAP_ENT(FORMAT_SPOUSE_OR_CIVIL_PARTNERS_FIRST_NAME),
	ERR_MAP_ENT(FORMAT_SPOUSE_OR_CIVIL_PARTNERS_NINO),
	ERR_MAP_ENT(FORMAT_SPOUSE_OR_CIVIL_PARTNERS_SURNAME),
	ERR_MAP_ENT(FORMAT_SRN_INVALID),
	ERR_MAP_ENT(FORMAT_START_DATE),
	ERR_MAP_ENT(FORMAT_STATUS),
	ERR_MAP_ENT(FORMAT_STRING),
	ERR_MAP_ENT(FORMAT_SUBMISSION_ID),
	ERR_MAP_ENT(FORMAT_TAX_YEAR),
	ERR_MAP_ENT(FORMAT_TO_DATE),
	ERR_MAP_ENT(FORMAT_TRANSACTION_ID),
	ERR_MAP_ENT(FORMAT_TYPE),
	ERR_MAP_ENT(FORMAT_TYPE_OF_BUSINESS),
	ERR_MAP_ENT(FORMAT_TYPE_OF_CLAIM),
	ERR_MAP_ENT(FORMAT_TYPE_OF_LOSS),
	ERR_MAP_ENT(FORMAT_UNIQUE_INVESTMENT_REFERENCE),
	ERR_MAP_ENT(FORMAT_VALUE),

	ERR_MAP_ENT(INVALID_TAX_YEAR_PARAMETER),

	ERR_MAP_ENT(MATCHING_RESOURCE_NOT_FOUND),

	ERR_MAP_ENT(MISSING_FROM_DATE),
	ERR_MAP_ENT(MISSING_TO_DATE),
	ERR_MAP_ENT(MISSING_TYPE_OF_BUSINESS),

	ERR_MAP_ENT(NO_BUSINESS_FOUND),
	ERR_MAP_ENT(NO_DETAILS_FOUND),
	ERR_MAP_ENT(NO_MESSAGES_PRESENT),
	ERR_MAP_ENT(NO_OBLIGATIONS_FOUND),

	ERR_MAP_ENT(PPD_SUBMISSION_ID_NOT_FOUND),

	ERR_MAP_ENT(RANGE_DATE_TOO_LONG),
	ERR_MAP_ENT(RANGE_END_DATE_BEFORE_START_DATE),
	ERR_MAP_ENT(RANGE_TO_DATE_BEFORE_FROM_DATE),

	ERR_MAP_ENT(RULE_ACCOUNTING_PERIOD_NOT_ENDED),
	ERR_MAP_ENT(RULE_ACCOUNTING_PERIOD_NOT_SUPPORTED),
	ERR_MAP_ENT(RULE_ACQUISITION_DATE),
	ERR_MAP_ENT(RULE_ACQUISITION_DATE_AFTER_DISPOSAL_DATE),
	ERR_MAP_ENT(RULE_ACTIVE_MARRIAGE_ALLOWANCE_CLAIM),
	ERR_MAP_ENT(RULE_ALREADY_EXISTS),
	ERR_MAP_ENT(RULE_ALREADY_SUBMITTED),
	ERR_MAP_ENT(RULE_AMOUNT_GAIN_LOSS),
	ERR_MAP_ENT(RULE_BENEFIT_TYPE_EXISTS),
	ERR_MAP_ENT(RULE_BOTH_ALLOWANCES_SUPPLIED),
	ERR_MAP_ENT(RULE_BOTH_EXPENSES_SUPPLIED),
	ERR_MAP_ENT(RULE_BSAS_ALREADY_ADJUSTED),
	ERR_MAP_ENT(RULE_BUILDING_NAME_NUMBER),
	ERR_MAP_ENT(RULE_BUSINESS_ID),
	ERR_MAP_ENT(RULE_BUSINESS_VALIDATION_FAILURE),
	ERR_MAP_ENT(RULE_CALCULATION_ERROR_MESSAGES_EXIST),
	ERR_MAP_ENT(RULE_CALCULATION_IN_PROGRESS),
	ERR_MAP_ENT(RULE_CESSATION_DATE_BEFORE_TAX_YEAR_START),
	ERR_MAP_ENT(RULE_CLASS4_OVER_16),
	ERR_MAP_ENT(RULE_CLASS4_PENSION_AGE),
	ERR_MAP_ENT(RULE_COMPLETION_DATE),
	ERR_MAP_ENT(RULE_COMPLETION_DATE_BEFORE_DISPOSAL_DATE),
	ERR_MAP_ENT(RULE_CONSOLIDATED_EXPENSES),
	ERR_MAP_ENT(RULE_COST_OF_MATERIALS),
	ERR_MAP_ENT(RULE_COUNTRY_CODE),
	ERR_MAP_ENT(RULE_CUSTOM_EMPLOYMENT),
	ERR_MAP_ENT(RULE_DATE_RANGE_INVALID),
	ERR_MAP_ENT(RULE_DATE_RANGE_OUT_OF_DATE),
	ERR_MAP_ENT(RULE_DECEASED_RECIPIENT),
	ERR_MAP_ENT(RULE_DEDUCTIONS_AMOUNT),
	ERR_MAP_ENT(RULE_DEDUCTIONS_DATE_RANGE_INVALID),
	ERR_MAP_ENT(RULE_DELETE_AFTER_CRYSTALLISATION),
	ERR_MAP_ENT(RULE_DELETE_FORBIDDEN),
	ERR_MAP_ENT(RULE_DISPOSAL_DATE),
	ERR_MAP_ENT(RULE_DUPLICATE_COUNTRY_CODE),
	ERR_MAP_ENT(RULE_DUPLICATE_PERIOD),
	ERR_MAP_ENT(RULE_DUPLICATE_SUBMISSION),
	ERR_MAP_ENT(RULE_DUPLICATED_PPD_SUBMISSION_ID),
	ERR_MAP_ENT(RULE_EARLY_SUBMISSION),
	ERR_MAP_ENT(RULE_END_DATE_BEFORE_START_DATE),
	ERR_MAP_ENT(RULE_END_DATE_BEFORE_TAX_YEAR_START),
	ERR_MAP_ENT(RULE_FHL_PRIVATE_USE_ADJUSTMENT),
	ERR_MAP_ENT(RULE_FINAL_DECLARATION_IN_PROGRESS),
	ERR_MAP_ENT(RULE_FINAL_DECLARATION_RECEIVED),
	ERR_MAP_ENT(RULE_FINAL_DECLARATION_TAX_YEAR),
	ERR_MAP_ENT(RULE_FROM_DATE_NOT_SUPPORTED),
	ERR_MAP_ENT(RULE_GAIN_AFTER_RELIEF_LOSS_AFTER_RELIEF),
	ERR_MAP_ENT(RULE_GAIN_LOSS),
	ERR_MAP_ENT(RULE_GROSS_AMOUNT_PAID),
	ERR_MAP_ENT(RULE_IGNORE_FORBIDDEN),
	ERR_MAP_ENT(RULE_INCOME_SOURCES_CHANGED),
	ERR_MAP_ENT(RULE_INCOME_SOURCES_INVALID),
	ERR_MAP_ENT(RULE_INCORRECT_DISPOSAL_TYPE),
	ERR_MAP_ENT(RULE_INCORRECT_GOV_TEST_SCENARIO),
	ERR_MAP_ENT(RULE_INCORRECT_OR_EMPTY_BODY_SUBMITTED),
	ERR_MAP_ENT(RULE_INSOLVENT_TRADER),
	ERR_MAP_ENT(RULE_INVALID_REQUEST),
	ERR_MAP_ENT(RULE_INVALID_SEQUENCE_START),
	ERR_MAP_ENT(RULE_IS_ANNUAL_ALLOWANCE_REDUCED),
	ERR_MAP_ENT(RULE_LATE_SUBMISSION),
	ERR_MAP_ENT(RULE_LOSS_AMOUNT),
	ERR_MAP_ENT(RULE_LOSS_CLAIMS_MISSING),
	ERR_MAP_ENT(RULE_LOSSES_GREATER_THAN_GAIN),
	ERR_MAP_ENT(RULE_LUMP_SUMS),
	ERR_MAP_ENT(RULE_MISALIGNED_PERIOD),
	ERR_MAP_ENT(RULE_MISMATCHED_END_DATE),
	ERR_MAP_ENT(RULE_MISMATCHED_START_DATE),
	ERR_MAP_ENT(RULE_NO_ACCOUNTING_PERIOD),
	ERR_MAP_ENT(RULE_NO_ADJUSTMENTS_MADE),
	ERR_MAP_ENT(RULE_NO_CHANGE),
	ERR_MAP_ENT(RULE_NO_INCOME_SUBMISSIONS_EXIST),
	ERR_MAP_ENT(RULE_NO_SUBMISSIONS_EXIST),
	ERR_MAP_ENT(RULE_NON_FHL_PRIVATE_USE_ADJUSTMENT),
	ERR_MAP_ENT(RULE_NON_MATCHING_PERIOD),
	ERR_MAP_ENT(RULE_NOT_CONTIGUOUS_PERIOD),
	ERR_MAP_ENT(RULE_NOT_FINALISED),
	ERR_MAP_ENT(RULE_NOT_FOREIGN_PROPERTY),
	ERR_MAP_ENT(RULE_NOT_SELF_EMPLOYMENT),
	ERR_MAP_ENT(RULE_NOT_UK_PROPERTY),
	ERR_MAP_ENT(RULE_OVER_CONSOLIDATED_EXPENSES_THRESHOLD),
	ERR_MAP_ENT(RULE_OVERLAPPING_PERIOD),
	ERR_MAP_ENT(RULE_PERIOD_NOT_ENDED),
	ERR_MAP_ENT(RULE_PERIODIC_DATA_INCOMPLETE),
	ERR_MAP_ENT(RULE_PROPERTY_INCOME_ALLOWANCE),
	ERR_MAP_ENT(RULE_PROPERTY_INCOME_ALLOWANCE_CLAIMED),
	ERR_MAP_ENT(RULE_RANGE_INVALID),
	ERR_MAP_ENT(RULE_RECENT_SUBMISSIONS_EXIST),
	ERR_MAP_ENT(RULE_RESIDENCY_CHANGED),
	ERR_MAP_ENT(RULE_RESULTING_VALUE_NOT_PERMITTED),
	ERR_MAP_ENT(RULE_SELF_EMPLOYMENT_ADJUSTED),
	ERR_MAP_ENT(RULE_SELF_EMPLOYMENT_ID),
	ERR_MAP_ENT(RULE_SEQUENCE_ORDER_BROKEN),
	ERR_MAP_ENT(RULE_SOURCE_INVALID),
	ERR_MAP_ENT(RULE_START_DATE_AFTER_TAX_YEAR_END),
	ERR_MAP_ENT(RULE_SUBMISSION_FAILED),
	ERR_MAP_ENT(RULE_SUMMARY_STATUS_INVALID),
	ERR_MAP_ENT(RULE_SUMMARY_STATUS_SUPERSEDED),
	ERR_MAP_ENT(RULE_TAX_YEAR_NOT_ENDED),
	ERR_MAP_ENT(RULE_TAX_YEAR_NOT_SUPPORTED),
	ERR_MAP_ENT(RULE_TAX_YEAR_RANGE_INVALID),
	ERR_MAP_ENT(RULE_TAX_YEAR_TOO_LONG),
	ERR_MAP_ENT(RULE_TO_DATE_BEFORE_FROM_DATE),
	ERR_MAP_ENT(RULE_TRADING_INCOME_ALLOWANCE_CLAIMED),
	ERR_MAP_ENT(RULE_TYPE_OF_BUSINESS),
	ERR_MAP_ENT(RULE_TYPE_OF_BUSINESS_INCORRECT),
	ERR_MAP_ENT(RULE_TYPE_OF_CLAIM_INVALID),
	ERR_MAP_ENT(RULE_UNALIGNED_DEDUCTIONS_PERIOD),
	ERR_MAP_ENT(RULE_UNIGNORE_FORBIDDEN),
	ERR_MAP_ENT(RULE_UPDATE_FORBIDDEN),
	ERR_MAP_ENT(RULE_VOLUNTARY_CLASS2_CANNOT_BE_CHANGED),
	ERR_MAP_ENT(RULE_VOLUNTARY_CLASS2_VALUE_INVALID),

	/* Generic top-level errors */
	ERR_MAP_ENT(BUSINESS_ERROR),
	ERR_MAP_ENT(INVALID_REQUEST),

	[MTD_HMRC_ERR_UNKNOWN] = {
		.str = "MTD_HMRC_ERR_UNKNOWN"
	}
};

enum mtd_hmrc_error mtd_hmrc_error(const char *json)
{
	json_t *jarray;
	json_t *root;
	json_t *result;
	json_t *code_obj;
	json_t *ecode_obj = NULL;
	json_t *errors;
	const char *code;
	int i;
	enum mtd_hmrc_error err = MTD_HMRC_ERR_UNKNOWN;

	jarray = json_loads(json, 0, NULL);
	root = json_array_get(jarray, json_array_size(jarray) - 1);
	result = json_object_get(root, "result");
	errors = json_object_get(root, "errors");
	if (errors && json_array_size(errors) > 1) {
		err = MTD_HMRC_ERR_MULTIPLE;
		goto out_free;
	} else if (errors) {
		ecode_obj = json_object_get(errors, "code");
		code_obj = ecode_obj;
	}

	/*
	 * You can get 1 or more HMRC errors returned from endpoints.
	 *
	 * Normally a single error would just be in the top level
	 * 'result' and multiple errors would be contained in an
	 * 'errors' array.
	 *
	 * However you can also get an errors array that only contains
	 * a single error and still have a top level error.
	 *
	 * Whether there's just a single error or multiple errors in
	 * the errors array, that will be the more specific error. So
	 * we want to check for that error first then fallback to the
	 * top level error.
	 *
	 * The reason for two separate loops for the two codes is so
	 * that we can put in generic codes like 'INVALID_REQUEST' &
	 * 'BUSINESS_ERROR' and we will only use them if we didn't
	 * find a more specific error code first.
	 */
	if (!ecode_obj)
		code_obj = json_object_get(result, "code");
	if (!code_obj)
		goto out_free;

	code = json_string_value(code_obj);
	for (i = 0; i < MTD_HMRC_ERR_UNKNOWN; i++) {
		if (strcmp(mtd_hmrc_err_map[i].str, code) != 0)
			continue;

		err = i;
		goto out_free;
	}

	if (!ecode_obj)
		goto out_free;

	code_obj = json_object_get(result, "code");
	code = json_string_value(code_obj);
	for (i = 0; i < MTD_HMRC_ERR_UNKNOWN; i++) {
		if (strcmp(mtd_hmrc_err_map[i].str, code) != 0)
			continue;

		err = i;
		break;
	}

out_free:
	json_decref(jarray);

	return err;
}
